### ISSUE TITLE
Allow reader conditionals in cljc files

### ISSUE THREAD

**Issue by facundoolano** [candid82/joker#1]
I'm using the linter for `cljc` files and it works good except for reader conditionals, which give the warning `No reader function for tag ?`. Also ClojureScript expressions inside those conditionals may show up as errors:

<img width="394" alt="screen shot 2017-02-17 at 9 19 04 am" src="https://cloud.githubusercontent.com/assets/1040941/23065097/8a1aaa7c-f4f2-11e6-969e-28be15386579.png">

Allowing the `#?` and maybe ignoring whatever's inside of them would be great.

Thanks for this project!

**Comment by candid82** [comment]
Properly linting inside reader conditionals would be challenging since it would require switching dialects on the fly, but ignoring symbol resolution errors inside `#?` should be relatively easy to implement. I'll see what I can do.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/e0d2fc38d441e8038db92f4cd8c0803e8250d29f
