### ISSUE TITLE
Unable to resolve symbol: double?

### ISSUE THREAD

**Issue by rmuslimov** [candid82/joker#10]
I'm getting this error on line:

`    >>>       15 (s/def ::original_total (s/and double? pos?))
`

am I miss something, or joker doesn't support `double?` function?

**Comment by candid82** [comment]
`double?` was added in Clojure 1.9 and I have not looked into 1.9 support yet (outside of https://github.com/candid82/joker/issues/6). After all, Clojure 1.9 is still in alpha :).  It should be trivial to add simple functions like this to Joker though.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/0450e04b9bd492429cda88340459d4c80a226005
