### ISSUE TITLE
In Git Bash for Windows, Joker REPL Exits After Prompt

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#103]
The screen looks like this:

```
craig@buck:~$ joker --repl -- a b c
Welcome to joker v0.10.0. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
craig@buck:~$
```

I can sometimes see the prompt briefly appear, so here's what `less` reveals:

```
Welcome to joker v0.10.0. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
^M^H^M^H^M^H^M^H^M^H^M^H^M^Huser=> ^M^H^M^H^M^H^M^H^M^H^M^H^M^H
(END)
```

**Comment by jcburley** [comment]
This is probably a `readline` issue, but I haven't (yet) experimented with using that outside of Joker (in a simple Go program) to confirm.

**Comment by jcburley** [comment]
(Note that `joker -e '(println "i am here")'` works fine.)

**Comment by jcburley** [comment]
Also, this works (aside from not catching EOF):

```
joker -e '(loop [input-string (read-line)] (println input-string) (recur (read-line)))'
```

**Comment by jcburley** [comment]
Could be this issue (which I asked about):

https://github.com/chzyer/readline/issues/109

**Comment by candid82** [comment]
Yep, looks like an issue in readline. There was an attempt to fix it [here](https://github.com/chzyer/readline/pull/141), but that PR was not merged, not sure why.

**Comment by candid82** [comment]
[This](https://github.com/candid82/joker/commit/58fffb5589b38aefc83c46b3dbb150616a3d0e32) commit allows to turn off joker's readline functionality by passing `--no-readline` flag. Of course this is not a real solution since repl is hard to use without readline and there is no rlwrap for Windows as far as I know (but it may work in cygwin).

**Comment by candid82** [comment]
Closing since this can only be fixed upstream.
