### ISSUE TITLE
Support Class Paths

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#105]
`(require ...)`, `(load ...)`, et al seem to load solely from the current directory (CWD), rather than searching through any sort of class path.

For production use, being able to put common `*.joke` files in a central library, and load them from there based on an environment variable (such as `JOKER_CLASSPATH`) containing a `$PATH`-style list of directories (semicolon-delimited on Windows, colon-delimited elsewhere), would allow Joker code to avoid having to hardcode the path(s) of such libraries.

**Comment by candid82** [comment]
Implemented by https://github.com/candid82/joker/pull/152. Thanks!
