### ISSUE TITLE
Using history and vi key-bindings with Joker REPL

### ISSUE THREAD

**Issue by asimjalis** [candid82/joker#107]
Is there a way to get history and vi key-bindings with the Joker REPL?

**Comment by jcburley** [comment]
Looks like you've already targeted the appropriate underlying component here:

https://github.com/chzyer/readline/issues/157

Have you tried the `rlwrap` utility? It seems to work with Joker, but I haven't tested it much, nor tried the `vim` key bindings it looks like it might support.

**Comment by asimjalis** [comment]
I tried rlwrap but it seemed to not have an effect on the behavior of the Joker REPL.

I ran it using `rlwrap joker`.

**Comment by asimjalis** [comment]
Readline supports Vim/Vi and history functionality through its configuration API. Here is an example of this. 

https://github.com/chzyer/readline/blob/2972be24d48e78746da79ba8e24e8b488c9880de/example/readline-demo/readline-demo.go#L112-L125

How can we expose this functionality to someone using the Joker REPL?

1. Enable Joker REPL config file that affects LineReader. Joker parses the config file and then calls the LineReader API.
2. Expose LineReader through the Joker Lisp language. This is a more flexible idea and might be simpler to implement. Is this already possible?

**Comment by candid82** [comment]
You can use `rlwrap` with Joker by passing `--always-readline` argument:

```
rlwrap --always-readline joker
```

This gives you full control over history and bindings as `rlwrap` uses GNU readline which is fully configurable via `.inputrc` file: https://linux.die.net/man/3/readline

I am thinking about providing a flag for Joker to turn its own readline functionality off to make wrapping with `rlwrap` more straightforward...

**Comment by candid82** [comment]
@asimjalis, see https://github.com/candid82/joker/commit/58fffb5589b38aefc83c46b3dbb150616a3d0e32. You can now do `rlwrap joker --no-readline` and get all the functionality of `rlwrap`, including history and vi bindings. Please give it a try and let me know if it works for you.

**Comment by candid82** [comment]
I feel like `rlwrap` + `--no-readline` is an adequate solution here. Closing.
