### ISSUE TITLE
"slice bounds out of range" when running joken on a simple example.

### ISSUE THREAD

**Issue by Gonzih** [candid82/joker#118]
Hey there, I just tried to run joker on a simple clj file and got a following error:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/candid82/joker/core.extractInt(...)
        /home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/pack.go:199
github.com/candid82/joker/core.UnpackHeader(0x0, 0x0, 0x0, 0xc0000b6180, 0xc0001723d0, 0x0, 0xbb3240, 0x4138d6)
        /home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/pack.go:102 +0x869
github.com/candid82/joker/core.processData(0x0, 0x0, 0x0)
        /home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/procs.go:1495 +0xba
github.com/candid82/joker/core.ProcessCoreData()
        /home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/procs.go:1505 +0x49
main.main()
        /home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/main.go:465 +0x37
```

This is my example `core.clj` file:

```clojure 
(ns myproject.core)

(defn printhi []
  (println "hello world!"))
```

This is the command I used:

```shell
 joker --lint --dialect clj core.clj
```

Is this a problem in my setup maybe? Can't figure out what's going on, any help is welcome :) Thanks!

**Comment by jcburley** [comment]
I can't reproduce this on my Mac OS X laptop using either 0.9.7 or current `master` (0.10.0 + commits).

What version of Joker are you using? Note that `joker --version` might work; otherwise leave off the option.

**Comment by candid82** [comment]
Are you using pre-built binary or did you build it yourself? What version are you using? What platform are you on?

**Comment by Gonzih** [comment]
Oh, tried to run --version, got this:
```
 joker --version
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/candid82/joker/core.extractInt(...)
	/home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/pack.go:199
github.com/candid82/joker/core.UnpackHeader(0x0, 0x0, 0x0, 0xc0000a4180, 0xc00015e3f0, 0x0, 0xbb3240, 0x4138d6)
	/home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/pack.go:102 +0x869
github.com/candid82/joker/core.processData(0x0, 0x0, 0x0)
	/home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/procs.go:1495 +0xba
github.com/candid82/joker/core.ProcessCoreData()
	/home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/core/procs.go:1505 +0x49
main.main()
	/home/gnzh/go-projects/pkg/mod/github.com/candid82/joker@v0.10.0/main.go:465 +0x37
```

Im on Arch Linux, my go version is `1.11.1`. I installed package from scratch, let me try AUR package instead.

**Comment by Gonzih** [comment]
Yeah, AUR package just works. Is this an issue related to master or is this difference between building from source and releasing?

**Comment by jcburley** [comment]
I don't understand the error well enough to say, but perhaps it has to do with changes made a short while ago with regard to how Joker initializes when it starts up (versus what's built right into it).

You might be able to build from `master` if you start with a clean tree. Earlier builds left artifacts that later ones not only didn't need, but got confused by.

Glad the problem is resolved!

**Comment by Gonzih** [comment]
I managed to reproduce this problem in docker container, so maybe this might be helpful:

```
docker run -ti golang bash
root@18901ac5fdbd:/go# go get github.com/candid82/joker/ && joker --version
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/candid82/joker/core.extractInt(...)
	/go/src/github.com/candid82/joker/core/pack.go:199
github.com/candid82/joker/core.UnpackHeader(0x0, 0x0, 0x0, 0xc0000721e0, 0x8, 0x10, 0xc000154420, 0x0)
	/go/src/github.com/candid82/joker/core/pack.go:102 +0x869
github.com/candid82/joker/core.processData(0x0, 0x0, 0x0)
	/go/src/github.com/candid82/joker/core/procs.go:1512 +0xba
github.com/candid82/joker/core.ProcessCoreData()
	/go/src/github.com/candid82/joker/core/procs.go:1522 +0x49
main.main()
	/go/src/github.com/candid82/joker/main.go:488 +0x37
```

Anyway, thanks for all your help and explanations, cheers!

**Comment by jcburley** [comment]
Try this instead -- it's a little more involved, but it ensures only a clean, full build is installed:

```
go get -d github.com/candid82/joker/ && cd $GOPATH/src/github.com/candid82/joker; ./run.sh joker --version && go install
```

I.e. pass the `-d` option to `go get` to stop after downloading, then go to the directory and build `joker` via its own `run.sh` script, passing `--version` to test it, and if that works, install it.

It works for me (not using Docker, just a fresh Go/github build directory), so I'll put in a PR or two for the `README.md` to clarify this.

(I wonder whether `go` supports some kind of build-time hooking so it'd all just work via `go get`?)

**Comment by candid82** [comment]
@Gonzih looks like AUR package is for the older version (v0.9.2). Could you please download [linux binary for v0.10.0](https://github.com/candid82/joker/releases/download/v0.10.0/joker-0.10.0-linux-amd64.zip) directly and see if it works on your system? As for building from source, try [instructions](https://github.com/candid82/joker#building) from readme or what @jcburley suggested (they should be more or less equivalent).
