### ISSUE TITLE
Allow linter to receive code text over stdin?

### ISSUE THREAD

**Issue by rgdelato** [candid82/joker#12]
I would love to be able to provide linter messages to the user while they're typing (before the file has been saved). I can provide both the current edited unsaved text and the file path, but I think I would need a way to pass the code text via the command line.

This is kind of a "nice-to-have", so I understand if it's out of scope, but it would be cool if this were possible.

**Comment by candid82** [comment]
This is already supported. Just pass `--` instead of a filename and Joker will read input from stdin. For example, `joker --lint --`. Sublime plugin [uses](https://github.com/candid82/SublimeLinter-contrib-joker/blob/master/linter.py#L22-L34) this feature.

**Comment by rgdelato** [comment]
Thank you so much. The Atom joker linter now has an option for linting on the fly!
