### ISSUE TITLE
False positive on extending print-dup

### ISSUE THREAD

**Issue by blak3mill3r** [candid82/joker#120]
For example this code:

```
(defmethod print-dup org.joda.time.DateTime
  [^org.joda.time.DateTime d ^java.io.Writer w]
  (#'i/print-date (java.util.Date. (.getMillis d)) w))
```

Which extends the multimethod `clojure.core/print-dup`

Produces the linter error:

`Unable to resolve symbol: print-dup`

**Comment by candid82** [comment]
Fixed by cf198a2f502621b0b121443d30fa9dfc871f188c
