### ISSUE TITLE
Create Test Suite for Evaluation of Expressions

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#131]
E.g. test the various combinations of reading from files versus strings, `\n` versus `\r\n` line endings, multiple lines, lack of final newlines, etc., when using `(read-line)`, potentially in combination with `(read)` and such, per:

https://github.com/candid82/joker/issues/129

**Comment by jcburley** [comment]
Could be kicked off by an `eval-tests.sh` script, to parallel `flag-tests.sh` and such.

Would add that to `.circleci/config.yml` as a final step.

**Comment by candid82** [comment]
Thank you for working on this!
