### ISSUE TITLE
Possibility of project level context for unused vars?

### ISSUE THREAD

**Issue by snoe** [candid82/joker#15]
I'm loving the unused vars linter but in my current project I'm finding that many public vars and some namespaces are simply never called or required elsewhere in the app.

It would be great if joker could somehow lint these as well. What are your feelings on this idea?

I see two possible ways to accomplish this. The first would be to simply take a list of source-dirs and write an index of used ns/vars to file, then subsequent​ lints of single files could read that index and call out missing vars while updating the index for it's calls.

The other way, a user provide a main fn and joker could statically trace calls, and produce a call graph with anything outside of the graph producing a warning. This graph could be useful for other cursive/intellij like analyses.

**Comment by snoe** [comment]
To add an example, if there's two files in a project foo.clj and bar.clj:
```clojure
(ns foo) (def a :used) (def b :unused)
(ns bar (:require [foo])) (println foo/a)
```


If I do something like `joker --index-usages foo.clj bar.clj` followed by `joker --lint foo.clj` it would be nice if `a` in `foo` was marked as unused

**Comment by candid82** [comment]
Project-wide dead code elimination would indeed be useful. I like the idea of using Joker for this kind of things, but implementation requires some thinking. It feels like this feature is more suitable for "offline" linting, when you run something like `joker --find-dead-code project.clj`, wait a few seconds and get the results printed out. I guess this corresponds to the second approach you suggested. The first approach (generate index file first, use it during regular linting) has the inherent problem of the index file getting out of sync with the source. And it's probably not that important to have such warnings during regular "on the fly" linting.
On the other hand I'd like to avoid creating too many options to handle special cases like this in joker executable. Maybe the right way to go about this is to have Joker do the heavy lifting of reading / parsing the code and expose the resulting AST via API. We have `read-string` already, why not add `parse` function that takes Clojure form and returns the AST? Then various code analysis tools for specific use cases (like dead code elimination) could be written as Joker scripts. What do you think? Not sure if this will fly, but it might be worthwhile experimenting with this approach...

**Comment by snoe** [comment]
I think the first option is a bit more appealing since it's a bit more batteries included like the linter, but I can see how the AST approach could be more powerful and lead to other advantages too. Maybe there's an option for project level type analysis.

**Comment by blak3mill3r** [comment]
FWIW @candid82 I like the sound of that approach with the AST API for joker. Let the editors have at it directly.

**Comment by candid82** [comment]
@blak3mill3r there is actually an undocumented function `parse__` that returns as AST. Try this: `joker -e "(pprint (parse__ '[1 2]))"`
Unfortunately that AST is not quite convenient to work with. I tried to implement something like what this issue describes, but ran into problems (don't remember the details) and abandoned the idea for the time being.  Feel free to take a stab at it if you'd like :)

**Comment by blak3mill3r** [comment]
That is really cool. I will ponder the possibilities.

**Comment by candid82** [comment]
Closing until better times.
