### ISSUE TITLE
Unary + Not Accepted -- Treated as Part of Symbol

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#156]
E.g.:

```
Welcome to joker v0.11.0. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user> +2
<repl>:2:1: Parse error: Unable to resolve symbol: +2
user=>
```

Compare:

```
Clojure 1.9.0
user=> +2
2
user=>
```

(Discovered while bringing Clojure tests over to address https://github.com/candid82/joker/issues/131.)

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/dcd5715665ca82a9f116b22bb5879d1972e656d6
