### ISSUE TITLE
(quot 4.0 2.0) Returns 2 (an Integer), not 2.0 (a Double)

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#159]
E.g.:

```
Welcome to joker v0.11.0. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user=> (quot 4.0 2.0)
2
user=> (type (quot 4.0 2.0))
Int
user=>
```

Compare:

```
Clojure 1.9.0
user=> (quot 4.0 2.0)
2.0
user=> (type (quot 4.0 2.0))
java.lang.Double
user=>
```

I'm actually a little surprised Clojure works the way it does, but am not going to quibble.

(Discovered while working on https://github.com/candid82/joker/issues/131.)

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/ff621cba26398da7dd15e001fe376c7bd3f4a24d
