### ISSUE TITLE
:require-macros with same namespace alias causes panic

### ISSUE THREAD

**Issue by snoe** [candid82/joker#16]
In ClojureScript, it's possible to alias macros under the same alias as non-macros. Joker panics in this situation. In core async, since the macros are in a different namespace than the functions it's desirable to alias them like this:

``` clojure
(ns example.macros
  (:require-macros [cljs.core.async.macros :as async])
  (:require [cljs.core.async :as async]))
```

```
$ joker --lint test.cljs
test.cljs:1:1: Eval error: Alias async already exists in namespace user, aliasing cljs.core.async.macros
Stacktrace:
  global test.cljs:1:1
  joker.core/require <joker.core>:3323:3
  joker.core/apply <joker.core>:509:4
  joker.core/apply__ <joker.core>:3243:9
  joker.core/apply <joker.core>:509:4
  joker.core/apply__ <joker.core>:3202:5
  joker.core/with-bindings* <joker.core>:1382:7
  joker.core/apply <joker.core>:507:4
  joker.core/apply__ <joker.core>:3217:9
  joker.core/alias <joker.core>:2372:3
```

**Comment by snoe** [comment]
Hi @candid82 do you have any thoughts on this?

**Comment by candid82** [comment]
Hey @snoe, thanks for reporting the issue and sorry it's taking me a while to get to it. I don't use ClojureScript often so tend to pay less attention to it, but I do want Joker to work well with ClojureScript, so keep feedback coming. 
The problem is that currently Joker naively treats `:require-macros` the same as `:require`, which is apparently not quite right even for linting purposes. I'll see what I can do to fix this.

**Comment by snoe** [comment]
No problem, and really, it's the panic that's the real issue. If joker emitted the duplicate ns as a warning or error that would be much better than currently where the rest of the file doesn't get linted because it crashes.

**Comment by candid82** [comment]
OK, this is somewhat alleviated by https://github.com/candid82/joker/commit/618e68aea4be76703997129d8a50e2c01ee9f806
It will still issue an error / warning, but it will proceed with linting the rest of the file.

**Comment by snoe** [comment]
Clojure 1.9 enforces unique aliases so I think this should be closed now.
