### ISSUE TITLE
Go 1.12 Dropping Support for 'go tool vet'

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#161]
This is per https://tip.golang.org/doc/go1.12#vet.

In particular:

> As part of this change, the experimental -shadow option is no longer available with go vet. Checking for variable shadowing may now be done using
> 
```
go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
go vet -vettool=$(which shadow)
```

**Comment by candid82** [comment]
I'll take care of this when migrating to Go 1.12. Thanks for reporting!

**Comment by jcburley** [comment]
Was curious about 1.12, so spent some time playing with it, and tried to fix the issue here:

https://github.com/candid82/joker/pull/166
