### ISSUE TITLE
Allow Joker to accept file path when reading via stdin

### ISSUE THREAD

**Issue by rgdelato** [candid82/joker#17]
When linting in my editor, Joker doesn't seem to respect the `.joker` file in my project root, and I think this is because when Joker is receiving input over stdin, it doesn't know where the file it's linting is located, and so doesn't know where to start looking for the `.joker` file.

Would it be a good idea to be able to pass the file path in addition to the unsaved text over stdin?

**Comment by candid82** [comment]
Looks like this can be addressed without introducing new arguments: https://github.com/rgdelato/linter-joker/pull/2
