### ISSUE TITLE
Duplicate Case Constants Undetected

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#170]
Unlike Clojure, Joker won't detect this:

```
(case "hey" :this :that :this :whatever :oy)
```

E.g. Clojure reports `Duplicate case test constant: :this`.

As an interpreter, it doesn't seem terribly important; but as a linter, it might be a good idea to do.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/229ce29a059300018c82626beab353d6c9611f78
