### ISSUE TITLE
Should "Bool" Be "Boolean" Instead, and "Int" "Integer"?

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#174]
Clojure calls it `Boolean`. Not sure why it's different in Joker....

**Comment by candid82** [comment]
Could have been Boolean... I think I just named it after Go `bool` type, similar to `Int`/`int`, although I did not follow this convention for other types like `Double` or `Char`. I don't think it matters honestly.

**Comment by candid82** [comment]
I do prefer shorter names if it's not at the expense of expressiveness, and `bool` is widely used / understood abbreviation.

**Comment by jcburley** [comment]
It's widely understood outside of Clojure-land, but Clojure using `Boolean` means Clojure code also uses `Boolean`. E.g. `^Boolean` or `:tag Boolean`, such as in `set.clj` in the Clojure source tree.

Seems kinda strange to have a different name for a common type, when the language being implemented is Clojure, just because it's common to use other names in other languages (like the implementation language here).

This is also an issue (to the extent it's much of an issue at all) for `Int` versus `Integer`, hence the Subject modification.

I'm not sure why Clojure chose the wordy spelling. I'm also not too thrilled about it...just want to make life easier for people going back and forth between Clojure implementations. (I'm also not thrilled about `map` not creating a map, when `vector` creates a vector, `set` creates a set, etc...but that's life in the world of functional/Lisp languages, where `map` is a common verb.)

**Comment by candid82** [comment]
Well, renaming `Int` to `Integer` would not be good since Java's (and Clojure's) `Integer` is a wrapper around `int`, which is 32-bit, whereas Joker's `Int` is a wrapper around Go's `int`, which is 64-bit on 64 bit platforms, so it's really equivalent to `Long`, not `Integer`. Perhaps the types should have been named `Long` and `Boolean`, but I don't really want to change the names now, unless it's causing real problems. One option could be adding `Long` and `Boolean` as aliases for `Int` and `Bool`, but this could potentially create confusion...

**Comment by jcburley** [comment]
Aha, great point about `Int`! And worth documenting.

I think `Long` should be done only if it becomes clear that people really need that data type in real-life Joker code.

Presumably if someone really wants to pull in generic Clojure code using `Integer` (as well as `Boolean`, I guess), they can define their own aliases.

But `Bool` -> `Boolean` still feels like a win to me, though as (still) a Clojure-ecosystem newbie, I'm not strongly opined towards it at this time.

Probably this should be Deferred, if you want to get into that level of details on what is (so far) a small handful of Issues.

I'm happy to help with (or do) the `Bool` renaming, though, if you're game.

**Comment by candid82** [comment]
OK, I am convinced about `Boolean`. See https://github.com/candid82/joker/commit/506bcde0f3b4758b7c447ab81aaba85611ee2dad.
