### ISSUE TITLE
Ignore unused :as bindings iff starting with underscore

### ISSUE THREAD

**Issue by tjbrandt** [candid82/joker#179]
Awesome work, @candid82. Using your linter at work every day.

In the documentation, you mention "Note that unused binding and unused parameter warnings are suppressed for names starting with underscore." However, in the case of `:as` bindings, it doesn't seem like names like `_unused-binding` are properly ignored.

I see that you can ignore all unused `:as` bindings with `:unused-as false` implemented in #59 , but I was wondering if, when set to the default `:unused-as true`, joker would still ignore unused `:as` bindings that are explicitly started with an underscore.

**Comment by candid82** [comment]
This already works as advertised (that is, no warnings):
```clojure
(let [{:keys [k] :as _unused-binding} {}] k)
```
Are you getting a warning on the code above? Perhaps you are using an old version of Joker?

**Comment by tjbrandt** [comment]
The above code was indeed giving me a warning, but you were right--I was using v0.10.0! Sorry! I got a new machine just a month or two ago so I didn't even think that I could be out of date. Now on 0.11.1, and works as you stated.

Thanks! I'll do my due diligence next time 😳
