### ISSUE TITLE
Wrong number of args (2) passed to #'joker.core/array

### ISSUE THREAD

**Issue by eneroth** [candid82/joker#18]
I spotted this in the [atom-parinfer](https://github.com/oakmac/atom-parinfer) source code. I suspect that it's guessing wrongly as to what `array` is being referenced in the code.

![screen shot 2017-08-01 at 08 17 58](https://user-images.githubusercontent.com/333974/28809129-55664152-7692-11e7-8188-3d8367f3f06b.png)

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/19129872c2eda90d5bdbb9ae5e24fcf1a059f5b6
