### ISSUE TITLE
read is valid with 3 args, but linter gives warning

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#182]
<img width="651" alt="screenshot 2019-02-28 10 26 38" src="https://user-images.githubusercontent.com/284934/53556106-81eab100-3b43-11e9-88c3-ab05f4c8e98a.png">

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/b38b2b7bcd4b31033fadad2ce34f9cffe7a540d2
