### ISSUE TITLE
Hangs when running --lint on Windows?

### ISSUE THREAD

**Issue by sparkofreason** [candid82/joker#19]
Downloaded and installed the 0.8.3 Windows binary. I can run "joker" and get a prompt, but running "joker --lint foo.clj" just burns CPU for several minutes, exits with no obvious output.

**Comment by sparkofreason** [comment]
This problem goes away when I add a .joker file.

**Comment by candid82** [comment]
Hey @sparkofreason, thanks for reporting the bug. I know what's causing the problem and will release the fix soon. In the meantime you can work around the issue by creating .joker file anywhere on the path between root and the file(s) you are linting.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/091de8c74d1969ea2c3815396a98a91c30f64553
