### ISSUE TITLE
Command line params not working?

### ISSUE THREAD

**Issue by arichiardi** [candid82/joker#192]
Hello folks!

It looks like there is something going on in the parameter parsing:

```
$ nix-env -i joker

$ joker -h
Error:  open -h: no such file or directory

$ joker -e '(println "Hello, world!")'
Error:  open -e: no such file or directory
```

Thanks for this tool it is awesome!

**Comment by candid82** [comment]
You might be using an old version of Joker that did not support `-h` or `-e` parameters. Please download the latest version and give it a try.

**Comment by arichiardi** [comment]
Indeed, the Nix version is outdated, the new release binary works like a charm.

Thank you, closing!
