### ISSUE TITLE
Common REPL functions missing

### ISSUE THREAD

**Issue by arichiardi** [candid82/joker#196]
Hello folks,

Great great project, I am excited to try it out and use it for some scripts.

My non-urgent issue is that while patching [`inf-clojure`](https://github.com/clojure-emacs/inf-clojure/pull/160) so that it can connect to a `joker` process I noticed that some of the common REPL functions are missing. Here is the list:
  
* `joker.repl/dir` 
* `joker.repl/source`
* `joker.repl/apropos`

It would be great to have them in if possible.

**Comment by jcburley** [comment]
Agreed! When I first created `joker.repl`, it was a quick-and-dirty thing to get just what I needed in. Wasn't sure anyone else would find it helpful. Intended to circle back and do this sometime...am looking at it right now, to see how easy it is. Thanks!

**Comment by candid82** [comment]
`dir` and `apropos` are now implemented thanks to @jcburley. `source` is not really feasible with current implementation and it certainly does not seem important enough to warrant major re-design.
