### ISSUE TITLE
Failure to build from source

### ISSUE THREAD

**Issue by SevereOverfl0w** [candid82/joker#198]
Using `go-1.12.1` causes `flag provided but not defined: -shadow` when running `./run.sh`. Looks related: https://github.com/etcd-io/etcd/pull/10454

**Comment by jcburley** [comment]
See my outstanding PR from awhile back (and note the discussion around it).

Until Joker officially migrates to Go 1.12, if you want to use it, you could try merging in that branch. Haven't tried it myself in awhile, so am not sure it'll work....

On March 23, 2019 2:58:59 AM EDT, Dominic Monroe <notifications@github.com> wrote:
>Using `go-1.12.1` causes `flag provided but not defined: -shadow` when
>running `./run.sh`. Looks related:
>https://github.com/etcd-io/etcd/pull/10454
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/candid82/joker/issues/198

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by SevereOverfl0w** [comment]
It seems to work, I've skipped the shadow step as it seems to just be a linter.

On March 23, 2019 12:04:02 PM GMT, James Craig Burley <notifications@github.com> wrote:
>See my outstanding PR from awhile back (and note the discussion around
>it).
>
>Until Joker officially migrates to Go 1.12, if you want to use it, you
>could try merging in that branch. Haven't tried it myself in awhile, so
>am not sure it'll work....
>
>On March 23, 2019 2:58:59 AM EDT, Dominic Monroe
><notifications@github.com> wrote:
>>Using `go-1.12.1` causes `flag provided but not defined: -shadow` when
>>running `./run.sh`. Looks related:
>>https://github.com/etcd-io/etcd/pull/10454
>>
>>-- 
>>You are receiving this because you are subscribed to this thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/candid82/joker/issues/198
>
>-- 
>Sent from my Android phone with K-9 Mail. Please excuse my brevity.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/candid82/joker/issues/198#issuecomment-475864252

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by candid82** [comment]
I've updated run.sh to work with Go 1.12: https://github.com/candid82/joker/commit/a7fb34e027487bd9b2cfe813597787a2cca438d0
