### ISSUE TITLE
nice to have: warn on unused vars

### ISSUE THREAD

**Issue by facundoolano** [candid82/joker#2]
I've found that using the joker linter is great to catch typos and syntax errors that I usually would miss until executing the code, so it's a huge time saver.

Comparing it to linters I use in other languages, I think it could benefit from showing a warning when a required or declared var is never actually used. This can help to catch stuff like you forgot some step in your logic, or you're not referencing the var you actually meant, or simply you didn't do the proper cleanup after a refactor.

Thanks for the good work!

**Comment by candid82** [comment]
This totally makes sense. Warnings on unused vars / bindings is near the top of my list of improvements I'd like to implement.

**Comment by candid82** [comment]
This is implemented in v0.7.2.

**Comment by facundoolano** [comment]
Awesome, thanks!
