### ISSUE TITLE
False positive on protocol methods

### ISSUE THREAD

**Issue by pithyless** [candid82/joker#201]
Thanks for the joker linter, it's been really useful!

One thing that bugs me is the false positive for unused parameters in `defprotocol`. I'm aware that I could just prefix all params with `_`, but that is an unaesthetic hack (changing how to name parameters for an optional linter). On the other hand, the unused parameters is a useful linter I wouldn't want to disable. Is this something we can change in `joker` itself? Or maybe I can just get around this with a custom rule?

```
❯ joker -v
v0.12.1

❯ cat foo.clj
(ns foo)

(defprotocol Foo
  (foo [this bar] "Implement magic."))

❯ joker --lint foo.clj
foo.clj:4:9: Parse warning: unused parameter: this
foo.clj:4:14: Parse warning: unused parameter: bar
```

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/07113111e5ec5814e6ecaac8262d6d1975aa2528
