### ISSUE TITLE
-1 for --hashmap-threshold not accepted

### ISSUE THREAD

**Issue by lread** [candid82/joker#203]
If I try the example in the README:
```
joker --hashmap-threshold -1 -e "(pprint (read))"
```
I get the following result:
```
Error: Missing argument for '--hashmap-threshold' option
```
I am running joker v0.12.1 installed via brew on macOS Mojave v10.14.4

**Comment by jcburley** [comment]
This looks like my bug, as I rewrote the command-line processing a few months ago.

Looks like my code treats `-1` (negative one) as an option and so doesn't consider it as a valid argument to a preceding option.

Will push a PR soon.
