### ISSUE TITLE
clojure/core.match "wildcards" is resulting in a parse error

### ISSUE THREAD

**Issue by pablohenriq** [candid82/joker#209]
Running the basic usage example of [clojure/core.match](https://github.com/clojure/core.match) is resulting in a parse error whose the message is `Unable to resolve symbol: _`.

The basic usage example I'm running is:
```clojure
(let [x true
      y true
      z true]
  (match [x y z]
    [_ false true] 1
    [false true _ ] 2
    [_ _ false] 3
    [_ _ true] 4
    :else 5))
;=> 4
```

Sorry if this issue is related with another existing issue, I could not be able to find it;

By the way, this is an excellent tool. Congrats.

**Comment by candid82** [comment]
This is a known limitation. Joker needs to know that `clojure.core.match/match` is a macro, not a function. This can be achieved by adding `clojure.core.match/match` to `:known-macros` in `.joker` file:

```
{:known-macros [clojure.core.match/match]}
```

Please read https://github.com/candid82/joker#reducing-false-positives for more details.

**Comment by pablohenriq** [comment]
I see. Thanks for your quick reply. This will certainly solve my problem for now.
