### ISSUE TITLE
joker --lint does not recognize namespace aliases created by `alias`

### ISSUE THREAD

**Issue by sparkofreason** [candid82/joker#21]
Namespace aliases created with the `alias` function don't seem to be recognized by the linter. For example, if I define `(alias 'stc 'clojure.spec.gen.test)` and later use `::stc/ret`, joker --lint will give an "Unable to resolve namespace stc" error.

**Comment by candid82** [comment]
Fix by https://github.com/candid82/joker/commit/21aeacd74152991f8993af9b47ee10ceeaa429f8. However, the namespace your are aliasing still needs to be required first, unless it's one of automatically loaded namespaces (for JVM Clojure, they are listed [here](https://github.com/candid82/joker/blob/master/core/data/linter_clj.joke#L54)). Correct me if I am wrong, but I don't believe `clojure.spec.gen.test` is automatically loaded, so Joker will complain that it cannot find that namespace if you alias it without requiring first. Perhaps a better way of accomplishing the same thing would be `(require '[clojure.spec.gen.test :as stc])`

**Comment by sparkofreason** [comment]
The problem is that `clojure.spec.gen.test` doesn't actually exist - it's one of those namespaces that exists just to qualify keywords. Requiring it will throw an error. This gets more common as one uses spec. I believe there is some discussion around including these "nonexistent" namespaces in the `ns` form in 1.9, not sure how that will pan out, and right now `alias` is the only solution.

**Comment by candid82** [comment]
Hm... If `clojure.spec.gen.test` doesn't exist, `alias` will fail:
```
test.core=> (alias 'stc 'clojure.spec.gen.test)

Exception No namespace: clojure.spec.gen.test found  clojure.core/the-ns (core.clj:4114)
```
Am I missing something?

**Comment by sparkofreason** [comment]
Right, sorry. The namespace "exists" via `create-ns`, it just doesn't contain any definitions, and was not created with the `ns` macro.

**Comment by candid82** [comment]
If `create-ns` happens in the same file, this should now work (see https://github.com/candid82/joker/commit/ce6e0f5381ba4f40657c460255aeb56faba53176). If it happens in a different file, Joker won't be able to understand this.

**Comment by candid82** [comment]
As a workaround, you can still add `(create-ns 'clojure.spec.gen.test)` in the file where you alias it, even it's already created elsewhere. This will make Joker happy and won't actually re-create the namespace. Does this make sense?

**Comment by sparkofreason** [comment]
Yes, makes sense, though I suspect we'll see a lot more of this as spec gets traction.

**Comment by candid82** [comment]
Do you think it makes sense to add something like `:known-namespaces` list to `.joker` file?

**Comment by sparkofreason** [comment]
Yes, that's a good idea.

**Comment by candid82** [comment]
This change https://github.com/candid82/joker/commit/becc73a0c7807880bf39e047f20f547991696723 should make it less of an issue - Joker will still issue a warning on `alias` because it cannot find the namespace, but it will lint the rest of the file and will not complain about symbols/keywords from the aliased namespace.

**Comment by candid82** [comment]
https://github.com/candid82/joker/commit/00d4482007472a755af69cc82e201f325dbbff64 adds `:known-namespaces` option to `.joker` file.
