### ISSUE TITLE
false positive type error when using with-meta

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#213]
<img width="416" alt="Screenshot 2019-04-25 17 51 21" src="https://user-images.githubusercontent.com/284934/56749935-01cb7b00-6783-11e9-99a6-00719b74a5cd.png">

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/2facf5f1eb899d5e7ea846a383e3893a932d94d3
