### ISSUE TITLE
Known symbol false positive in linter

### ISSUE THREAD

**Issue by harold** [candid82/joker#215]
Hi, thanks again for joker, we're really digging it and it's helping a lot every day.

Whilst debugging I'm often throwing `clojure.pprint/pprint` in various places in namespaces that don't necessarily require `clojure.pprint`. This works, because my live repl session has required the namespace elsewhere.

Is there a way (perhaps in `.joker`) to specify known symbols to quash this false positive.

**Comment by candid82** [comment]
Add `clojure.pprint` to `:known-namespaces` in your .joker file. I recommend reading [this part](https://github.com/candid82/joker#reducing-false-positives) of the readme for more tips on how to reduce false positives.

**Comment by harold** [comment]
Super! I had missed that option. :bowing_man: Thank you for your time and insight.
