### ISSUE TITLE
Unexpected end of file on conditional read

### ISSUE THREAD

**Issue by harold** [candid82/joker#217]
Hi, I hope these are helpful and not annoying. Working on getting one of our sizable codebases joker clean and finding these issues. :smile: 

```
harold@wintermute:~ []$ cat test.cljc 
(ns test)

#?(:cljs "foo")
harold@wintermute:~ []$ joker --lint ./test.cljc 
./test.cljc:4:0: Read error: Unexpected end of file
```

Hope that helps, and thanks as ever.

**Comment by candid82** [comment]
This is definitely helpful and not annoying at all. This is a legit issue, and it's already fixed by https://github.com/candid82/joker/commit/8b8d5e83b79b3cb269af6a3c60da34881df8295a (there was a [similar issue](https://github.com/candid82/joker/issues/195) reported some time ago).

**Comment by harold** [comment]
Great! Glad to be of service.
