### ISSUE TITLE
joker --lint failure in cljc require with reader conditionals, exception stops the process

### ISSUE THREAD

**Issue by langmartin** [candid82/joker#22]
this might actually be two issues, the first is with one-armed reader contionals

    (ns user (:require [clojure.set :as set] #?(:cljs foo.bar)))

which throws

    Read error: Unexpected )

The other valid syntax for contional require where the clj platform has no matching requirement is

    (ns user (:require [clojure.set :as set] #?@(:clj [] :cljs [foo.bar])))

which throws

    cljc:1:1: Eval error: No value supplied for key true

my system:

    joker --version v0.8.3
    ls ~/.joker No such file or directory

**Comment by sparkofreason** [comment]
I don't think reader conditional splicing via `#?@` is currently supported by joker. I ran into your first issue was well, currently working around it by having separate `ns` declarations for `:clj` and `:cljs`.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/d0f9de5e243b7e7b26346dd54372ff84445c31a6
