### ISSUE TITLE
joker.os/exec

### ISSUE THREAD

**Issue by Gavlooth** [candid82/joker#221]
Hard as i may try, i am not able to use exec with {:pipe :stdin} option. :pipe with string works really good, but I want to use pipeline stdin to joker. Not sure if this is pottentialy a bug or lack of documentation (and my understanding)

**Comment by Gavlooth** [comment]
It seems to work now, dont know what the issue was
Sure, one or two examples would help

**Comment by candid82** [comment]
@Gavlooth there was a bug in `joker.os/exec` that is now [fixed](https://github.com/candid82/joker/commit/f0e093341cf5c916ffb99e51bcc1227dc3e655a3). This now works:

```
> echo hi | ./joker -e '(pprint (joker.os/exec "cat" {:stdin :pipe}))'
{:success true,
 :exit 0,
 :out "hi\n",
 :err ""}
```
