### ISSUE TITLE
Parse error when reading `*print-namespace-maps*`

### ISSUE THREAD

**Issue by bhb** [candid82/joker#222]
Repros on Joker v0.12.3

Repro:

```clojure
;; example.clj

(ns example)

(binding [*print-namespace-maps* true]
  {:foo/bar 1})
```

`joker --lint example.clj`

Expected: Should lint as normal
Actual: `Parse error: Unable to resolve symbol: *print-namespace-maps*`

Clojure source that sets up binding for `*print-namespace-maps*` https://github.com/clojure/clojure/blob/b19b781b1f0f3f46aee5e951f415e0456a39cbcb/src/clj/clojure/main.clj#L89

Note this doesn't happen for other dynamic vars like `*print-level*`

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/706362c6798b6ef75144676469ece695a965dc14
