### ISSUE TITLE
cljs: Exception: Unsupported option(s) supplied: :refer-macros

### ISSUE THREAD

**Issue by Wonko7** [candid82/joker#223]
Hi all!

This is my first time using joker, so I may be doing something wrong. 
When I try to run `joker --lint --dialect joker src/project/core.cljs` 
I get: `src/project/core.cljs:8:22: Exception: Unsupported option(s) supplied: :refer-macros`

This is the offending bit of code: 
```
(ns project.core
  (:require
    [project.db :as db]
    [project.routes :as routes]
    [project.mail :as mail]
    [project.auth :as auth]
    [project.lol :as lol]
    [taoensso.timbre :refer-macros [log trace debug info warn error fatal]]
    [cljs.core.async :refer [chan <! >! timeout] :refer-macros [go go-loop] :as a]
    [utils.asyncawait :refer [await] :refer-macros [async alet]]
    [utils.helpers :refer [rand-hex l i sleep]]
    [axios :as axios]
    [process :as process]))

...
```

**Comment by candid82** [comment]
Change `--dialect` to `cljs` (since this is ClojureScript code you are linting) or omit `--dialect` argument altogether, dialect will be inferred based on the filename extension:
```
joker --lint --dialect cljs src/project/core.cljs
```
or 
```
joker --lint src/project/core.cljs
```

**Comment by Wonko7** [comment]
Thanks!
