### ISSUE TITLE
Integrated joker with Kakoune

### ISSUE THREAD

**Issue by w33tmaricich** [candid82/joker#225]
Hey @candid82! Thanks for writing joker. Just started using it the other day and its great.

I just wanted to let you know I wrote a script that can be used to utilize joker within the text editor [Kakoune](https://kakoune.org). I saw on your readme there were links to different editors that supported joker, and i just wanted to let you know Kakoune now does too!

Here is a link to the [project repository](https://github.com/w33tmaricich/clj-kakoune-joker) if you are interested in adding it.

Thank you again for writing joker! Its a super awesome tool, and now its one of my daily drivers.

Hope you are well,
Alexander

**Comment by candid82** [comment]
@w33tmaricich this is great, thanks a lot! I've added a link to your project in the readme.
