### ISSUE TITLE
symbol is not a function in joker

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#226]
```
echo "('foo '{foo 1})" | joker
Welcome to joker v0.12.3. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
<repl>:1:3: Eval error: foo is not a Fn
```

**Comment by jcburley** [comment]
What behavior were you expecting?

**Comment by jcburley** [comment]
Just tried this in Clojure and now I understand what is expected here: the symbol, as a function, should look itself up in the map provided by the argument, and return the value (`1` in this case).

**Comment by borkdude** [comment]
Right, as joker is also a linter, this results in a false positive.

**Comment by jcburley** [comment]
PRs surely welcome!

(It might be an enjoyable task for me to work on, except I'm still in the midst of moving from NYC to GA (outside ATL), and my main development machine (running Ubuntu 16.04) crashed -- literally crashed -- when the movers dropped it from a height of over 10' from the truck as they unloaded! I can use my laptop for "light" development work, but prefer the workstation for serious stuff....)

**Comment by borkdude** [comment]
@jcburley Don't worry, I just came across this when linting several things myself in [clj-kondo](https://github.com/borkdude/clj-kondo) and I noticed that joker gave this message. I'm not using this in production code. As I'm not so fluent in Go, I don't think I'll have a PR ready for this anytime soon...

![Screenshot 2019-05-25 16 37 37](https://user-images.githubusercontent.com/284934/58371120-e8972500-7f0e-11e9-8fa2-5f7743a8d250.png)

**Comment by candid82** [comment]
@borkdude thanks for reporting! This is fixed by https://github.com/candid82/joker/commit/47ec6e610f6df1ba60d98b567229065237efbce6

@jcburley sorry to hear about the accident with your machine, hope you'll recover soon!
