### ISSUE TITLE
`~/.jokerd/linter.clj` no longer respected as of `v0.11.0`

### ISSUE THREAD

**Issue by blak3mill3r** [candid82/joker#229]
I discovered today that after upgrading to `v0.12.4` my `~/.jokerd/linter.clj` file is no longer respected... I tracked down the most recent tag that works the way I expect and found that `v0.10.2` works and `v0.11.0` does not.

To stop it warning about `"Unable to resolve symbol: x"` when using `:refer :all` with `com.rpl.specter`'s *many* symbols as described in https://github.com/candid82/joker/issues/50 I have a `linter.clj` file that begins with this:

```clojure
;; -*- mode: clojure; eval: (flycheck-mode -1); -*-
;;; my dev tooling
(defmacro >>> [& args])
;;; clojure.test
(defmacro deftest [& args])
(defn use-fixtures [& args])
;; (defn testing [& args])
;; (defn is [& args])
;;; specter
(defn  index-nav  [& args])
(defn  indexed-vals  [& args])
(defn  srange-select*  [& args])
;; lots and lots more elided...
```

Did `v0.11.0` introduce a bug, or perhaps something else changed about the linter configuration and I am simply not aware of it?

**Comment by candid82** [comment]
@blak3mill3r you need to add `(in-ns 'joker.core)` at the top of your `~/.jokerd/linter.clj` file. See the explanation here: https://github.com/candid82/joker/releases/tag/v0.11.0

> Joker now evaluates in-ns when linting. This results in more accurate error messages (pointing to the current namespace rather than user namespace). IMPORTANT: if you have .jokerd/linter.* files, you might have to add (in-ns 'joker.core) at the top to make sure your definitions reside in joker.core namespace and are therefore referred in the namespace being linted.
