### ISSUE TITLE
Macros required via :refer-macros not known to joker

### ISSUE THREAD

**Issue by n2o** [candid82/joker#23]
I am not quite sure if this is too specific, but there is an issue with referred macros in ClojureScript and om.next. I'll show you an example:

    $ joker -v
    0.8.4

![image](https://user-images.githubusercontent.com/1507474/29997709-ac61ce94-901a-11e7-883d-325b34b46f19.png)

The tooltip says "Unable to resolve symbol: HelloWorld" etc.

Console output:

```shell
$ joker --lint hello.cljs
hello.cljs:9:8: Parse error: Unable to resolve symbol: HelloWorld
hello.cljs:13:3: Parse error: Unable to resolve symbol: Object
hello.cljs:14:4: Parse error: Unable to resolve symbol: render
```

This is not really a big thing, but I wanted to add this for completeness, because I really like your project and there will be many people developing ClojureScript and seeing this false-positive. 

Thanks for your work! I'd help you with this, but I can't program Go...

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/2b0d4977b952b1c06dc215dcf156a250a90a60de. Thanks for reporting. I don't use ClojureScript on a regular basis, so any feedback is appreciated.

**Comment by n2o** [comment]
Awesome, thank you!
