### ISSUE TITLE
try / catch / finally not documented

### ISSUE THREAD

**Issue by hlship** [candid82/joker#234]
Noticed that the joker docs don't include anything for `try` and `catch` (and `finally`).

Also, it looks like where I might use `Throwable` in Java Clojure, I use `Error` in Joker.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/e14878e0c10d40f408bc6a8a812e61a3279bc596. E.g. https://candid82.github.io/joker/#throw
