### ISSUE TITLE
ex-cause failed

### ISSUE THREAD

**Issue by amadev** [candid82/joker#239]
joker -v
v0.12.4

1) calling ex-cause on ex-info w/o cause leads to panic

(try
  (throw (ex-info "Exec failed" {:cause "cause"} ))
  (catch Error e
    (printf "err %s %s\n" (ex-message e) (ex-cause e))))
fails with SIGSEGV
panic: <file>:0:0: Exception: Exec failed [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x71decb]
...
http://ix.io/1N1C

2) specifying 'cause' arg has strange effect:

user=> 
user=> (try
user=>   (throw (ex-info "Exec failed" {:cause "cause"}))
user=>   (catch Error e
user=>     (printf "err %s %s\n" (ex-message e) (ex-data e))))
err Exec failed {:cause cause}
nil
user=> 

user=> (try
user=>   (throw (ex-info "Exec failed" {:cause "cause"} "cause"))
user=>   (catch Error e
user=>     (printf "err %s %s\n" (ex-message e) (ex-data e))))
err nil nil
nil

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/7aa68e731944cd52b75dba16f4e7ed5110580d89
