### ISSUE TITLE
Support `:known-tags` for tagged literals

### ISSUE THREAD

**Issue by sparkofreason** [candid82/joker#24]
Datomic's `#db/fn` tagged literal is current flagged with an error "No reader function for tag db/fn". Perhaps a `:known-tags` feature would mitigate this? This particular case also has the possibility of introducting local symbols in the `:params` attribute, would be nice-to-have to avoid that, but it's a pretty limited use-case.

**Comment by candid82** [comment]
Thanks for the suggestion! This is implemented by https://github.com/candid82/joker/commit/e53d66766844b8d118ba9331dcacf944844e40b5. Symbol resolution inside `known-tags` will work the same way it works for `known-macros`, so introducing local symbols won't cause false positives.
