### ISSUE TITLE
SQLite support?

### ISSUE THREAD

**Issue by rcarmo** [candid82/joker#245]
I realize this would mean a (beefy) extra dependency like [go-sqlite3](https://github.com/mattn/go-sqlite3) (which requires `cgo` and more testing), but accessing SQLite databases would be an awesome addition to Joker's scripting capabilities.

**Comment by candid82** [comment]
I understand the appeal of having built-in SQL engine for some use cases, but I think it would bring the disproportional amount of additional complexity. Perhaps exploring CGO (which I don't know much about) and potential uses of it in Joker should be the first step here... If anyone wants to experiment with the idea, I'd be curious to see what it could look like, but I probably won't work on things like this any time soon.

**Comment by pmonks** [comment]
My (extremely limited!) understanding is that the use of `cgo` would limit cross-compilation, which would be a real shame.  I'm using `joker` on an old Raspberry Pi (cross compiled from macOS), and it works very well.  I'd be sad to lose that.
