### ISSUE TITLE
Integrated help/version/summary call

### ISSUE THREAD

**Issue by lxsli** [candid82/joker#246]
https://dev.to/hlship/joker-flex-your-scripting-muscles-in-almost-clojure-2ph8

A bunch of this could be considered boilerplate. Would you be open to a `joker.tools.cli` function that allows something like:

```
(defn set-defcon ...)

(def opts
  [["-d" "--defcon VALUE" "Set DEFCON level"
    :parse-fn atoi
    :validate [#(<= 1 % 5) "level must be 1 to 5"]])

(cli/standard
  {:name "CoolScript"
   :opts opts
   :version "1"}
  (fn [{:keys [defcon]} arguments fail]
    (some? defcon) (set-defcon defcon)
    :else
    (do (println "Must specify a value for --defcon")
        (os/exit -1))))
```

It feels like the `:else` should be handled by `parse-opts`, but that's probably a separate issue.

**Comment by candid82** [comment]
This version may be a bit shorter, but the code doesn't read too well IMO.  I think I prefer more explicit approach. Perhaps this discussion should be first taken to https://github.com/clojure/tools.cli ?
