### ISSUE TITLE
Using `pprint` with BigDecimal causes strange rounding

### ISSUE THREAD

**Issue by matthewdowney** [candid82/joker#247]
Hey there! I'm trying to use Joker's `pprint` functionality to pretty print highlighted EDN structures in Vim. I've noticed that pretty printing anything via `pprint` containing BigDecimals changes the BigDecimal values (looks like float rounding) whereas using `joker.json` leaves them intact.

For example:
```
~$ echo "[206500M -0.04600485M]" | ./joker -e '(pprint (read))'
[206500M

-0.04600485000000000000000000000000000000000000000000000000000000000000000000000002427108810723742717518580327521424295466440742421172520447061623256181040360768500372312468775851883192576211490625901457299502608017650298784240181504401334677822887897491455078M]
~$ echo "[206500M -0.04600485M]" | ./joker -e '(joker.json/write-string (read))'
"[206500,-0.04600485]"
```

For my specific case, expanding to pretty printed JSON is also easier on the eyes, but it would be even cooler if I could pretty print EDN while scrolling through log files. Does any easy fix come to mind?

Thanks!

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/ff39132df4f9f09a5f0dfefae725da57ddf97b19

**Comment by matthewdowney** [comment]
Amazing, thanks for the quick fix!
