### ISSUE TITLE
Unable to build for linux/arm/6

### ISSUE THREAD

**Issue by pmonks** [candid82/joker#248]
In trying to cross-compile v0.12.6 for an (old) Raspberry Pi B+:
```
go clean
go generate ./...
export GOOS=linux
export GOARCH=arm
export GOARM=6
go vet ./...
go build
```

(note: due to the use of `//go:generate go run` directives in `core/object.go`, we can't run the `go generate` step after establishing the desired target environment - doing so results in go attempting to run a linux/armv6 binary on the host.  This may be part of the problem?)

We see:
```
# github.com/candid82/joker/std/time
std/time/a_time.go:13:24: constant 3600000000000 overflows int
std/time/a_time.go:17:26: constant 60000000000 overflows int
```

Any ideas?

**Comment by pmonks** [comment]
I'm not familiar with go, but it seems like the size of the `int` data type is platform specific.  Perhaps being explicit throughout the joker codebase with either `int32`, or (more likely) `int64`, will help with this problem?

**Comment by jcburley** [comment]
Looks like the same problem that was fixed, post-release, by https://github.com/candid82/joker/issues/243.

Try pulling the latest `master` branch. This invocation of `go build` works for me:

```
$ GOOS=linux GOARCH=arm GOARM=6 go build
$
```

**Comment by pmonks** [comment]
Oh nice - I’ll give that a shot later today and report back.

I’m intrigued to see Joker’s performance on this platform. Clojure on the JVM is hellishly slow, and I’ve been unable to get either planck or lumo to build on this platform.

**Comment by jcburley** [comment]
I'm hoping there's lots of room for improvement in Joker startup time (based on perf analysis I did about a year ago, of Lisp implementations generally and Clojure specifically, as well as of startup times for minimal programs in C, Go, Java, etc.)

Maybe by the end of this year, we can realize at least some such gains.

Once up and running, though, Joker remains an interpreter, vs the compiled code delivered by CLJ and CLJS. So they should win out at some point, at the expense of startup time and memory footprint due to JIT compilation that doesn't burden Joker.

On August 20, 2019 10:55:50 AM EDT, Peter Monks <notifications@github.com> wrote:
>Oh nice - I’ll give that a shot later today and report back.>
>>
>I’m intrigued to see Joker’s performance on this platform. Clojure on
>the JVM is hellishly slow, and I’ve been unable to get either planck or
>lumo to build on this platform. >
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/candid82/joker/issues/248#issuecomment-523053049

--
http://burleyarch.com/

**Comment by pmonks** [comment]
Ok `master` built and ran great!

And it's reasonably quick too - several orders of magnitude faster than Clojure JVM on this same platform:

```
pi@retropie:~ $ time ./joker -e '(+ 1 1)'
2

real	0m4.974s
user	0m1.772s
sys	0m0.249s
```

Not bad given the paltry hardware specs:

```
pi@retropie:~ $ lscpu
Architecture:          armv6l
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Model:                 7
Model name:            ARMv6-compatible processor rev 7 (v6l)
CPU max MHz:           700.0000
CPU min MHz:           700.0000
BogoMIPS:              697.95
Flags:                 half thumb fastmult vfp edsp java tls
```

**Comment by jcburley** [comment]
Wow, that's great!

Can you reply with the timing for Clojure (and maybe lumo or something using a JS engine, if you can get it to build)?

And, as I said, I have high hopes we can make startup time faster. Golang itself does not seem to be much of a limiting factor, AFAICT.

**Comment by pmonks** [comment]
Well it took longer, and a lot more faffing about, than I'd hoped, but here are the results for the latest JVM I could find for this platform (and Clojure 1.10.1):

```
$ java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) Client VM (build 25.221-b11, mixed mode)
$ time clojure -e '(+ 1 1)'
2

real	0m43.526s
user	0m37.589s
sys	0m1.845s
```

**Comment by jcburley** [comment]
Wow, that's a lot slower (versus Joker) than I expected! Glad to see Joker performs as well as it does.

**Comment by jcburley** [comment]
For what it's worth, I see a similar factor of difference (on my new Ryzen 3900x system w 32GB):

```
$ time joker -e '(+ 1 1)'
2

real	0m0.034s
user	0m0.045s
sys	0m0.007s
[$ time clojure -e '(+ 1 1)'
2

real	0m1.242s
user	0m3.634s
sys	0m0.153s
$
```

(Just two samples in the midst of doing each of them repeatedly.)

**Comment by pmonks** [comment]
Your Ryzen system may be _marginally_ more capable than my Raspberry Pi B...
