### ISSUE TITLE
False positives with clojure.spec.alpha/fdef

### ISSUE THREAD

**Issue by n2o** [candid82/joker#25]
It is common practice to specify a function prior its implementation.. But when I do this with joker-linting enabled, it says "Unable to resolve symbol: add".

For example:
```
(require '[clojure.spec.alpha :as s])

(s/fdef add
        :args (s/cat :x int? :y int?)
        :ret int?)

(defn add
  "Insecure add. Not the best idea."
  [x y] (+ x y))
```

That is just a small thing, just a nice-to-have feature to remove this false-positive. I am usually using joker in combination with flycheck (I even created a small [spacemacs-layer](https://github.com/n2o/clojure-lint-spacemacs-layer) for it) and I have always this warning in my editor ;-)

Thank you!

**Comment by candid82** [comment]
@n2o, add `clojure.spec.alpha/fdef` to `:known-macros` list in your `.joker` file, this should solve the issue. See [Reducing false positives](https://github.com/candid82/joker#reducing-false-positives) for details.

**Comment by n2o** [comment]
Okay, that is a solution. Thanks!
