### ISSUE TITLE
run.sh Fails for Cross-platform Builds

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#250]
This was mentioned in https://github.com/candid82/joker/issues/248#issue-482644818.

The problem is that `go generate` and `tools/sum256dir/` are run at build time, but with the target platform in effect (due to `$GOOS` and `$GOARCH` being defined).

**Comment by candid82** [comment]
Hm... why would one want to run `run.sh` with cross compiling? Even if it compiles, would not it fail to start since it's build for a different platform? Or am I missing something?

**Comment by candid82** [comment]
I consider `run.sh` a helper script for development. When releasing, I just run `GOOS=<os> GOARCH=<arch> go build` (actually, I just run `build-all.sh` that runs that command for three supported platforms).

**Comment by jcburley** [comment]
LOL, it _is_ called `run.sh` (not `build.sh`) after all, so good point!

As I'm primarily a developer, I think of it as a build script (and usually invoke it via my own ad-hoc generic `build` tool).

I'll withdraw the PR and maybe just offer one for `README.md`.
