### ISSUE TITLE
Guide for adding new namespaces?

### ISSUE THREAD

**Issue by rcarmo** [candid82/joker#252]
Hello there - I'm trying to create my own namespace to extend `joker`, and I can't quite figure out how to go about it.

I've cloned the repo, added a new folder inside `std` and a matching `.joke` file, wrote `a_` and `_native` stubs for what I want to invoke and modified `generate-std.joke` to add the new namespace, but it doesn't get compiled in.

Is there a documented way to add new functionality to Joker?

Thanks!

**Comment by jcburley** [comment]
See https://github.com/candid82/joker/blob/master/core/data/README.md, which we should modify based on your experiences getting it to work.

E.g. you shouldn't have to write an `a_*.joke` file yourself -- it's autogenerated by `generated-std.joke`.

**Comment by jcburley** [comment]
BTW, what does your new namespace do?

**Comment by rcarmo** [comment]
Thanks! I'll look into it. I'm trying to write a wrapper for [sqlite-lite](http://github.com/bvinc/go-sqlite-lite), since #245 was closed, I would find it extremely useful and it seems straightforward enough when compared to other `sqlite` libraries.

I'll report back when I have reproducible steps or feedback for that README file...

**Comment by pmonks** [comment]
sqlite support would be great!  I'm a little nervous about introducing a requirement on `cgo` however, since my (limited!) understanding is that that prevents cross-compilation (something I'm doing with `joker`).

**Comment by rcarmo** [comment]
Well, I’m using a library that does work on the Raspberry Pi, and developing on one, so that’s part of my goals.

**Comment by pmonks** [comment]
My understanding is that *cross compilation* is substantially more difficult once `cgo` is in the mix, even when the C libraries that are being interfaced with are available on the target platform.

Happy to be proven wrong, but just want to make it clear that there's value (to me, at least) in preserving the ease with which `joker` can be cross-compiled.

**Comment by rcarmo** [comment]
Well, I have a fair bit of experience with cross-compilation (not Go, plain C/C++) and have of late simplified matters a great deal for my container workflows: https://github.com/rcarmo/azure-pipelines-multiarch-docker/blob/master/README.md

I’m sure joker can ultimately built by native toolchains in an emulated CPU if we have any trouble with cgo...

**Comment by candid82** [comment]
I think this issue is now addressed by https://github.com/candid82/joker/blob/master/DEVELOPER.md (thanks @jcburley!)

**Comment by rbucker** [comment]
Since the joker authors already do code generation in the build they could add a flag that generated stubs for cgo-based API when cross compiling. **However**,  If the one example against a particular feature is `cgo` to a raspberry Pi then it seems [a] the needs of the one... [b] the "one" does not understand the purpose of cross-compiling.

**Comment by pmonks** [comment]
@rbucker the code generation in the `joker` build generates go code (easy to cross compile), not C code (harder to cross compile).  The original discussion here was around integrating `sqlite`, a library that is implemented in C, not go, and hence (if integrated with joker) would increase the complexity around cross compilation.
