### ISSUE TITLE
What are the limitations of the type checking?

### ISSUE THREAD

**Issue by didibus** [candid82/joker#255]
Hi,

To my delight I realized Joker can type check type hints in linter mode.

I wanted to know, how full blown is that? Is there any limitations to it? Or can it fully type check everything even indirectly which is type hinted?

Regards

**Comment by candid82** [comment]
It's very rudimentary. Many core functions are type hinted (when it makes sense), so that Joker knows expected types of parameters and return values. It then tries to infer actual types of passed arguments and see if there is a mismatch. It can only infer types in trivial cases like literals and core function calls. It will also check argument types for user defined functions if they are type hinted:

```clojure
(defn f [^Int t] t)

(f "foo")  // warning: type mismatch
(f (str 1)) // warning: type mismatch
(+ "foo") // warning: type mismatch
(+ (str 1)) // warning: type mismatch
```

**Comment by didibus** [comment]
It seems the user defined functions, it only applies to functions defined in the same namespace? So if `f` was defined in another namespace, and called with an alias, the type hint wouldn't show.

Also it seems that not all types are checked in linter mode? For example:

```
(defn f [^int t] t)

(f "foo")  // I don't get a warning
```

but

```
(defn f [^Number t] t)

(f "foo")  // I do get a warning
```

Is that all correct?

**Comment by didibus** [comment]
Also, it seems for user defined return type hints it uses the wrong type hint:

```
(defn f ^String [^Number t] t)

(+ (f 12)) ;; This does not warn
```
```
(defn ^String f [^Number t] t)

(+ (f 12)) ;; This does warn
```

But only the former is valid fn return type hint as per doc: https://clojure.org/reference/java_interop#typehints it says: For function return values, the type hint can be placed before the arguments vector

Regards

**Comment by candid82** [comment]
Yes, Joker issuing type warning for user defined functions is more of a side effect than an actually designed feature. It doesn't work across multiple namespaces / files (Joker only reads one file when linting). It only works with function arguments and only for types with the same name in Joker and Clojure (like `String` or `Number`).
