### ISSUE TITLE
Linter: also lint code inside a comment expression

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#26]
Is it possible to also lint code inside a comment expression?

```
(foo x) ;; Unable to resolve symbol: foo
(comment
  (foo x) ;; No warning
)
```

**Comment by candid82** [comment]
It should be easy enough to enable parsing / linting inside `comment`, but it may cause false positives or negatives if the code inside `comment` depends on code outside `comment` and vice versa. For example:

```clojure
(defn ^:private foo []) ;; do we issue "unused var" warning or not?
(comment 
  (foo)
  (defn bar []))
(bar) ;; this is clearly a problem, but requires special handling of symbol interns inside `comment`
```

Making it work properly in all edge cases is not worth it.

**Comment by borkdude** [comment]
OK, I understand the problem with this. Thanks.
