### ISSUE TITLE
joker.os/sh ClojureCLR Clojure.Main.exe

### ISSUE THREAD

**Issue by pwhittin** [candid82/joker#266]
Executing the following:

(joker.os/sh "Clojure.Main.exe")

Returns immediately with ":success true".  

I expected Clojure.Main.exe to display it's prompt let me use its REPL.

**Comment by candid82** [comment]
This is addressed by https://github.com/candid82/joker/commit/0a196a40245a2fbe1e9b8f9a7044da32ce75ddeb. You need to pipe all three (stdin, stdout, stderr) to achieve interactive behavior. Here is Joker invoking Joker:
```
> ./joker
Welcome to joker v0.12.7. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user=> (joker.os/exec "joker" {:stdin :pipe :stdout :pipe :stderr :pipe})
Welcome to joker v0.12.7. Use EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user=> (+ 1 2)
3
user=> ^D
{:success true, :exit 0}
user=> ^D
```

Let me know if this work with `Clojure.Main.exe` on Windows.

**Comment by pwhittin** [comment]
I built a Windows version of Joker at 0a196a4, executed the following script with it on Windows 7, and everything works perfectly.  Thanks!

(joker.os/chdir "clojure")
(joker.os/exec "Clojure.Main" {:args ["--init" "user.clj" "--repl"] :stdin :pipe :stdout :pipe :stderr :pipe})

**Comment by candid82** [comment]
Yep, the docs will be updated with the next release of Joker.

**Comment by candid82** [comment]
@pwhittin I changed the API a bit. See https://github.com/candid82/joker/commit/2cc38ef305885b74e13828da41354e706e6f7186#diff-5d6ba22b772d49152895e5ebe06136a1R57-R62
The options for interactive calls should now be `{:stdin *in* :stdout *out* :stderr *err*}`. New API also allows to redirect stdin/out/err to/from files, e.g.

```
(joker.os/exec "cat" {:stdin (joker.os/open "f1.txt") :stdout (joker.os/create "f2.txt")})
```

I'd appreciate if you could build the latest master and test your scenario on Windows with this change.

**Comment by pwhittin** [comment]
I built a Windows version of Joker at d84f172, executed the following script with it on Windows 7, and everything works perfectly, and the docs are correct. Thanks!

(joker.os/chdir "clojure")
(joker.os/exec "Clojure.Main" {:args ["--init" "user.clj" "--repl"] :stdin *in* :stdout *out* :stderr *err*})
