### ISSUE TITLE
Don't complain about escape character

### ISSUE THREAD

**Issue by MicahElliott** [candid82/joker#27]
Joker complains about the `\033` escape sequence.  Using `\e` is also problematic.  These are commonly needed for ansi escape terminal sequences, like color printing.

    (defn foo []
      (println "\033[31mFOO\033[0m"))  ; print FOO in red

    % joker --lint src/foo/core.clj
    src/foo/core.clj:151:17: Read error: Unsupported escape character: \0

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/74e327591279f562741f6404f08bab213a583c49
