### ISSUE TITLE
Strings are nilable in Clojure

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#272]
Joker should probably not warn about this:

```
(defn foo [^String x])
(foo nil)
```

The output is:

```
/tmp/foo.clj:5:6: Parse warning: arg[0] of user/foo must have type String, got Nil
```

**Comment by candid82** [comment]
Technically you are right, but this looks like a bit contrived example. Moreover, I'd argue that normally a function with type hinted argument would expect an actual string and may not necessarily handle `nil` gracefully. 
I am happy to revisit this issue if I see a real life example, but as it stands right now I am not sure it's worth fixing.
