### ISSUE TITLE
Clojure linter returns unhelpful error on empty destructuring map

### ISSUE THREAD

**Issue by lverns** [candid82/joker#273]
given a file `bug.clj`
```clojure
(ns bug)

(defn f
  [{}]
  :k)
```

This is valid Clojure, but it is somewhat silly. It would be better to use the traditional `_` to indicate that `f`'s argument is not used.

But if we run the linter against it:
```
$ joker --lint --dialect clj bug.clj 
<file>:0:0: Parse warning: unused binding: map__2
```
The exit code is `1`.

I'm not sure what the desired behavior would be in this scenario, but if the linter is going to raise a warning on this code it should at least have the correct location specified (`bug.clj:4:3:`).

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/80dba73b85020e4c77565b14175e167155573bbe
