### ISSUE TITLE
IntelliJ IDEA/Cursive and Joker Socket REPL

### ISSUE THREAD

**Issue by pwhittin** [candid82/joker#275]
**Steps To Reproduce**

**Step 1**: Execute 
```bash
joker --repl localhost:4321
```
**Step 2**: In IDEA create a "Clojure REPL Remote" "RemoRun/Debug Configuration" with Host=localhost and Port=4321 named "Joker REPL".

**Step 3**: Run "Joker REPL", which results in the following output in the IDEA REPL window:

```bash
Connecting to remote nREPL server...
Exception starting REPL: java.lang.ArithmeticException: integer overflow
```

**Comment by jcburley** [comment]
Might help to have the architecture info (`go env GOOS GOARCH`), as this could be a 32-bit-integer issue.

**Comment by pwhittin** [comment]
> go env GOOS GOARCH
linux
amd64

**Comment by candid82** [comment]
The error (`java.lang.ArithmeticException`) is coming from the client side (Cursive) as Joker has nothing to do with Java.
Joker doesn't support nREPL protocol which is what Cursive seems to use.

**Comment by pwhittin** [comment]
What protocol does Joker use?

**Comment by jcburley** [comment]
Joker supports only Socket REPL (sREPL) -- just a regular REPL, but accessed via a network socket.

I haven't looked into what an nREPL requires. Maybe after I finish my current Joker work, I'll check it out? (Adding the sREPL was fairly easy....)

**Comment by pwhittin** [comment]
I'm trying to configure a development environment that can be used to do "interactive" Joker development similar to IDEA/Cursive/Clojure.  I'm sure one can create a plugin for most popular IDEs to use sREPL for interacting with Joker.  I was just hoping to avoid that level of effort :)

**Comment by candid82** [comment]
FWIW, Joker [should work](https://github.com/clojure-emacs/inf-clojure/pull/160) with emacs inf-clojure mode.
