### ISSUE TITLE
Possible (apply merge maps) Bug

### ISSUE THREAD

**Issue by pwhittin** [candid82/joker#276]
I'm running Joker v0.12.7 commit bb5b1dc4896f9f8319139cd9653c416b09b0de4a.  Also:
```bash
> uname -a
Linux pauwhi-pc 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
and 
```bash
> go env GOOS GOARCH
linux
amd64
```

If I execute the following code several times I get different results, and some of them look like they have errors.
```clojure
(defn map-entry->string-map-entry [me]
      {(str (key me)) (str (val me))})

(defn map->string-map [m]
      (map map-entry->string-map-entry m))

(pprint
  (sort-by
    #(str %)
    (->> (all-ns)
         (map str)
         (map symbol)
         (map ns-publics)
         (map map->string-map)
         flatten
         (apply merge))))
```
Interestingly, if I remove the **(apply merge)** the results are always the same.

Additionally, if I execute:
```clojure
(pprint
  (->> (all-ns)
       (map str)
       (map symbol)
       (map ns-publics)
       (map map->string-map)
       flatten))
```
and create a **def** named "maps" with the output, and execute
```clojure 
(pprint (apply merge maps))
```
several times the results are always the same.

The attached ZIP file contains a test the reproduces the bug.  Create a directory named **bug** in the Joker directory, extract the ZIP file content into it, and execute the following from within the **bug** directory:
```bash
./run.sh
```
to run the test.

[possible-apply-merge-bug.zip](https://github.com/candid82/joker/files/3691079/possible-apply-merge-bug.zip)

**Comment by candid82** [comment]
I have not looked into this in detail, but the fact that your code returns different results doesn't surprise me. `(all-ns)` returns elements in random order, so does `(ns-publics`). After `(flatten)` is called, you have a seq of key/value pairs in random order, and some of the keys are the same (e.g. `read-string` from `joker.core` and `read-string` from `joker.json`). So after `(apply merge)`, the last value for the same key ends up in the result, and that value may be different every time you run the code.

**Comment by pwhittin** [comment]
That makes sense.
