### ISSUE TITLE
Support map namespace syntax

### ISSUE THREAD

**Issue by vlaaad** [candid82/joker#29]
Clojure 1.9 introduces [map namespace syntax](https://clojure.org/reference/reader), which allows to write
```
#:person{:first "Han" :last "Solo"}}
```
which is read as
```
{:person/first "Han" :person/last "Solo"}
```
Currently joker complains about this:
```console
vlaaad@ubuntu ~/P/transportal> joker --lint src/common/clj/transportal/seeder.clj
src/common/clj/transportal/seeder.clj:237:7: Read error: Reader tag must be a symbol
```
It would be great if joker supported such syntax

**Comment by candid82** [comment]
Implemented by https://github.com/candid82/joker/commit/b250bb4aba4abce95668c9b6784f94ee42d543f1
