### ISSUE TITLE
Socket prepl support

### ISSUE THREAD

**Issue by Olical** [candid82/joker#296]
Hey! I'm the author of [Conjure](https://github.com/Olical/conjure) (Clojure + ClojureScript tooling for Neovim over a socket prepl), I had a request (https://github.com/Olical/conjure/issues/70) to add support for Joker which would be awesome.

It would require Joker to support a socket prepl though, which I've detailed in a [blog post](https://oli.me.uk/clojure-prepl-for-tool-authors/). What do you think about that? If it's doable, it'd be really cool, if it's kind of too far out of what you care about for Joker then no worries.

I don't need the support, but it might be a nice use case. You could then have a full async REPL experience through Neovim + Joker, which might be appealing to you? Mainly opening this issue to get your thoughts, no pressure!

Thanks for the brilliant tool, I use it to lint all of my code, catches so many of my mistakes _before_ I eval.

**Comment by candid82** [comment]
Hey @Olical, thanks for submitting this issue. I think in general it makes sense for Joker to have prepl support since Clojure has it, but I'll have to look into it more for cost/benefit analysis.

**Comment by Olical** [comment]
For the record, Conjure now supports nREPL for Clojure. If you'd like an interactive REPL experience tailored for Joker I can write a client for it since Conjure is now a shell containing multiple specific client implementations for different language and transport mechanism combinations 🎉

**Comment by candid82** [comment]
Closing as there is not much interested in this right now.
