### ISSUE TITLE
Problems building v0.8.5

### ISSUE THREAD

**Issue by andrestylianos** [candid82/joker#30]
First of all, thank you for all the work you are putting into this. Using flycheck-joker for linting in emacs became part of my daily coding.

For this reason, I was trying to package joker for the [nix package manager](https://nixos.org/nix/) which I've been using a lot lately, but I ran into a problem as currently, I am unable to build v0.8.5 from source, seeing as I get this error:
```
building
../std/generate-std.sh: line 4: joker: command not found
```

I am able to build the master branch and if I understood correctly the issue I'm having was fixed with the commit "Commit joker generated files". Would there be a plan for releasing a new version with the latest fixes soon? I'd love to be able to finish packaging it for use in nix, whenever a new version is out (Hope this sounds good to you!).

**Comment by candid82** [comment]
Yep, `v0.8.5` requires Joker to generate part of the source code for itself. And yes, you are right, it will no longer be required once that commit is released. I am planning on cutting a new release this week.

Thank you for your support. It would be great to have Joker package for nix!

**Comment by andrestylianos** [comment]
Awesome! Looking forward to it :)

**Comment by candid82** [comment]
`v0.8.6` is out.
