### ISSUE TITLE
print-table

### ISSUE THREAD

**Issue by quan-nh** [candid82/joker#308]
I found that function like `clojure.pprint/print-table` is miss. Can we have it in the `core` or `pprint` ns? The same code as in clojure [print_table.clj](https://github.com/clojure/clojure/blob/master/src/clj/clojure/pprint/print_table.clj) just work fine with joker as well.

**Comment by candid82** [comment]
Added in https://github.com/candid82/joker/commit/76d1281c29c7d15bf16769a77ae03166672e1a05
