### ISSUE TITLE
Support tilde expansion in some way

### ISSUE THREAD

**Issue by crocket** [candid82/joker#309]
Currently, I cannot execute

```
(ns abc
  (:require [joker.os :as os]))

(os/exec "./launch.sh" {:dir "~/app/abc"
                        :stdout *out* :stderr *err*})
```

**Comment by jcburley** [comment]
It would be great to have "native" support for tilde expansion in Joker, but that would probably just wrap whatever such support Go and its libraries provided.

In the meantime, this might be worth reading:

https://stackoverflow.com/questions/17609732/expand-tilde-to-home-directory

If you have trouble converting some of the (simpler) Go code snippets into Joker code, give a holler. One hint is that `(get (joker.os/env) "HOME")` might prove useful.

**Comment by crocket** [comment]
`(get (joker.os/env) "HOME")` is good for now although a more concise solution is desirable.

**Comment by candid82** [comment]
https://github.com/candid82/joker/commit/d0def9fa4ce915dbfcc322400c19a657783910b1 adds `joker.os/get-env` function.
