### ISSUE TITLE
Specify whether joker uses java string literals or Go string literals.

### ISSUE THREAD

**Issue by crocket** [candid82/joker#310]
I don't know which is the case by reading the documentation.

**Comment by jcburley** [comment]
In what context? For Joker code itself, the syntax for a string is the same as is for Clojure.

Or are you asking about something other than syntax? Joker doesn't provide any Java interoperability. Its strings are implemented via the Joker `String` type, which is a Go `struct` that has a member `S: string`, i.e. the underlying builtin `string` type provided by the Go language.

Could you identify one or more places where the documentation could be clarified in this regard?

**Comment by crocket** [comment]
I want to write escape sequences in joker source files, but Go and java have different escape sequences.

**Comment by candid82** [comment]
Turns out there was a silly bug in octals reading code. Fixed by https://github.com/candid82/joker/commit/4881f032ab8706b1ba9a219bac313498030385d3. Thanks for reporting!
