### ISSUE TITLE
Support launching daemonized processes.

### ISSUE THREAD

**Issue by crocket** [candid82/joker#311]
```
#!/usr/bin/env joker
;; -*- mode: clojure; -*-
(ns my-fork
  (:require [joker.os :as os]))

(apply os/sh (concat
              '("setsid" "-f")
              *command-line-args*))
```

doesn't actually fork from the calling terminal. For now,

```
#!/bin/sh

setsid -f "$@" >/dev/null 2>&1
```

is my solution.

**Comment by crocket** [comment]
It may be possible to work around the issue with command line daemonizers.

**Comment by candid82** [comment]
Can you elaborate on what you are trying to achieve? Without the context the issue description is a bit cryptic.

**Comment by crocket** [comment]
I wanted to launch a web browser in newsboat which is a curses terminal fead reader.
To not disrupt newsboat rendering and newsboat interface, the launched process needs to be daemonized.

A workaround is to use command line daemonizers.

**Comment by candid82** [comment]
Gotcha. FWIW, this works: `(joker.os/sh "sh" "-c" "nohup sleep 10000 &>/dev/null &")`. Maybe that's what you mean by "command line daemonizers".

**Comment by crocket** [comment]
That is difficult to understand because I don't fully understand `nohup` and `&`.
I was thinking about https://github.com/bmc/daemonize/

**Comment by candid82** [comment]
OK. In any case, it doesn't seem like there is anything that needs to be done in Joker. Closing.
