### ISSUE TITLE
Do joker.os/exec and joker.os/sh discard :out and :err?

### ISSUE THREAD

**Issue by crocket** [candid82/joker#312]
I wonder whether joker.os/exec and joker.os/sh discard :out and :err if they are not used.

If a program's output is larger than memory and joker doesn't discard the output, the computer may run out of memory.

**Comment by candid82** [comment]
`joker.os/sh` always captures `:out` and `:err` as strings. `joker.os/exec`, on the other hand, allows you to redirect `:out` and `:err` to any file, including `/dev/null`:
```clojure
(joker.os/exec "ls" {:stdout (joker.os/create "/dev/null") :stderr (joker.os/create "/dev/null")})
```

I believe "nul" would be "/dev/null" equivalent on Windows, but I have not tested it as I don't have any Windows machine nearby. (Perhaps @jcburley could help confirm this).

Joker still opens "/dev/null" file and pipes the program output to it, so it's not as efficient as not capturing the output to begin with, but it should work for cases when you want to discard large outputs.

**Comment by candid82** [comment]
After looking into the Joker code and reading Go's documentation I think the above code will actually connect the programs output directly to `/dev/null` file, so it *is* pretty efficient.

**Comment by crocket** [comment]
That's good enough.
