### ISSUE TITLE
limitations of only being able to pass a single flag to the linter

### ISSUE THREAD

**Issue by nicwest** [candid82/joker#32]
I recently wrote a linter for https://github.com/w0rp/ale (a vim plugin for async linting). Joker works really really well for this due to it's fast startup speed and nice outputs.

However having spent a couple of days using it I started running into an issue where joker didn't seem to detect my `.joker` file. Looking deeper into the issue, I found it was because ale was writing the contents of my file to a `/tmp/xzy.clj` file then linting that, loosing the context of the original sources directory and thus its `.joker` file. 

Swapping the ale linter to pipe the files contents to stdin worked... until I changed directory and again lost the context of my working directory. finally frustrated I swapped the linter to just read the file off the disk and now it only works on saving the file.

Ideally I would like to add a flag to the linter to parse in the config directly:

`joker --lint --config='{:known-macros [bar/def-something foo/another-macro ...]}' <filename/stdin>`

or

`joker --lint --config='/path/to/file/.joker' <filename/stdin>`

or 

`joker --lint --working-dir='/path/to/file/' <filename/stdin>`

however [the current main](https://github.com/candid82/joker/blob/45137442e3125b9441cba00c91afb15c1f1e969a/main.go#L200-L229) doesn't leave much leeway in terms of adding additional flags.

Instead of parsing `os.Args` manually something along the lines of the [flag](https://golang.org/pkg/flag/) lib would give more flexibility. I had a mess about last night converting it use [pflag](https://github.com/spf13/pflag) just to see if it would work and it appears functional ([if a bit ugly](https://github.com/candid82/joker/compare/master...nicwest:flags)).

Is this something that seems reasonable? I don't want to break anything in the repl/interpreter.

**Comment by candid82** [comment]
Thanks for working on this! The code looks fine to me, feel free to submit a PR. As for new flag, I think `--working-dir` for the case of reading from `stdin` makes the most sense and should solve the original problem. Also, feel free to submit a PR to add a link to your ale linter.

Thanks!

**Comment by candid82** [comment]
This has been addressed by #34. Thanks @nicwest!

**Comment by candid82** [comment]
Looks like this broke one important use case: when Joker script accepts its own flags. For example, if `script.joke` takes `-s` flat, running `joker script.joke -s` will result in an error: `unknown shorthand flag: 's' in -s`.

**Comment by nicwest** [comment]
bugger, I was worried I would overlook something

I've written some tests, but it looks like we aren't going to be able to use any of the flag varients for this :(

```clj
(testing "script args don't cause errors"
  "tests/flags/script-flags.joke -go-style-flag -otherflag"
  "[joker script-flags.joke -go-style-flag -otherflag]"

  "tests/flags/script-flags.joke --unix-style-flag --otherflag"
  "[joker script-flags.joke --unix-style-flag --otherflag]"

  "tests/flags/script-flags.joke --unix-style-flag-with-value foobar"
  "[joker script-flags.joke --unix-style-flag-with-value foobar]"

  "tests/flags/script-flags.joke --unix-style-flag-with-value=foobar"
  "[joker script-flags.joke --unix-style-flag-with-value=foobar]"

  "tests/flags/script-flags.joke --short-hand-flags -a -b -c"
  "[joker script-flags.joke --short-hand-flags -a -b -c]"

  "tests/flags/script-flags.joke --short-hand-flags -abc"
  "[joker script-flags.joke --short-hand-flags -abc]"

  "tests/flags/script-flags.joke -- something that is not a flag"
  "[joker script-flags.joke -- something that is not a flag]")
```

```clj
; tests/flags/script-flags.joke
(println (joker.os/args))
```

I would suggest reverting for the moment

**Comment by candid82** [comment]
I think we still need `--working-dir` parameter and I also like `--dialect`. I'll probably implement the same functionality without relying on `pflags` library and with passing arguments to the script properly. I am not seeing any way to achieve this with `pflags` :(

**Comment by candid82** [comment]
@nicwest I finally fixed the issue (by parsing flags manually). Also added slightly modified tests you provided. Thanks again for your contributions!

**Comment by nicwest** [comment]
Cheers @candid82 I have been feeling guilty about this for weeks, but did have the time to fix it :(

**Comment by jcburley** [comment]
I've looked at the `pflag` code, and it seems like it treats `--` as ending the options _it_ processes:

https://github.com/spf13/pflag/blob/master/flag.go#L1090  (see: "--" terminates the flags)

So that might allow (if Joker's interpretation of `--` changed to conform to this canonical behavior):

```
$ joker [joker-opts] -- [scriptname] [script-opts]
```

Maybe that's good enough? But people might expect this to work as well, and I'm not sure `pflags` supports it:

```
$ joker [joker-opts] [scriptname] [script-opts]
```

That is, once the scriptname appears, everything after that should be treated as arguments to the script, not to Joker itself.

**Comment by candid82** [comment]
I think the second form should be supported by Joker as well (it currently is) as this is pretty common use case for interpreters.

**Comment by jcburley** [comment]
Agreed -- even beyond interpreters, utilities (such as `time` and `xargs`) that wrap command invocations typically offer the second form as the primary, if not only, way.

I'm not sure whether `pflag` is going to support this properly, but I might try looking into offering a PR myself, and will add it as an issue in the meantime. 

Note: by "properly", I mean that I don't think https://github.com/spf13/cobra/issues/623 is a proper fix for this, though it's clearly an attempt to do so and might meet the use cases envisioned there without any issues.

In particular, it relies on the flags after `scriptname` being actually "unknown" with respect to Joker  (and the flags it defines as "known") itself.

That suggests that, if there's a "collision" between `scriptname` and Joker itself, in that they both support the same option name, it'd get processed by Joker (perhaps with an error, if there's a type incompatibility) and not passed to `scriptname`, even if it came after `scriptname` on the original command line.

**Comment by jcburley** [comment]
Good news! I discovered (when looking into making the change to `pflag` myself) that the feature is already there, via e.g.:

```
pflag.SetInterspersed(false)
```

It has the desired behavior, though for now we can't use it because `--` is treated the canonical way:

```
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit 
t1=false t2=false t3=5
#args=0 command-with-args=[]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit x a b --t1 --t3 6
t1=false t2=false t3=5[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ !2040
./wrapit 
t1=false t2=false t3=5
#args=0 command-with-args=[]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ !2041
./wrapit x a b --t1 --t3 6
t1=false t2=false t3=5
#args=6 command-with-args=[x a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ !2042
./wrapit --t2 x --t3 7 a b --t1 --t3 6
t1=false t2=true t3=5
#args=8 command-with-args=[x --t3 7 a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit --t2 -- --t3 7 a b --t1 --t3 6
t1=false t2=true t3=5
#args=7 command-with-args=[--t3 7 a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit --t2 - --t3 7 a b --t1 --t3 6
t1=false t2=true t3=5
#args=8 command-with-args=[- --t3 7 a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$
#args=6 command-with-args=[x a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit --t2 x --t3 7 a b --t1 --t3 6
t1=false t2=true t3=5
#args=8 command-with-args=[x --t3 7 a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit --t2 -- --t3 7 a b --t1 --t3 6
t1=false t2=true t3=5
#args=7 command-with-args=[--t3 7 a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$ ./wrapit --t2 - --t3 7 a b --t1 --t3 6
t1=false t2=true t3=5
#args=8 command-with-args=[- --t3 7 a b --t1 --t3 6]
[1] craig@doe:~/.go/src/github.com/jcburley/wrapit$
```

(See the link to the `pflag` issue I raised, above, for the source code to the program, adding the new call just before `pflag.Parse()`.)

So, when `--` is seen, it's treated (by `pflag`) to mean "remaining arguments should not be processed and are available in `pflag.Args()`"; while `-` means "if `.SetInterpersed(true)` is in effect, __this and the__ remaining arguments should not be processed and are available in `pflag.Args()`.

Once we are prepared to reclaim `--` for its canonical meaning, perhaps we can resurrect https://github.com/candid82/joker/pull/34/commits/90bbd1f6815fcd64a6f3ea30773707a0e8926bca et al and refresh as needed.
