### ISSUE TITLE
[REQ] Add a joker.core/uuid function

### ISSUE THREAD

**Issue by hlship** [candid82/joker#329]
I'd like some way to generate a UUID, or a UUID string.

**Comment by candid82** [comment]
I was hoping Go would provide this in its standard library, but apparently this is not the case, so this will require some research.

**Comment by jcburley** [comment]
This seems to be the latest canonical implementation, though it would still add a new dependency:

https://github.com/google/uuid

**Comment by candid82** [comment]
Yes, I was thinking about (partially) copying the code from there rather than adding the whole thing as a dependency. I *think* their license allows it as long as the attribution is preserved.

**Comment by hlship** [comment]
In a pinch, you can shell out to the `uuid` command ...

**Comment by candid82** [comment]
Just landed in master:
```
user=> (joker.uuid/new)
"5b7822ca-02a0-4ccf-85d2-32eed0a756fe"
```
