### ISSUE TITLE
Replace gen_data With Something Better

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#363]
After https://github.com/candid82/joker/issues/362 is done, it might be worth replacing `gen_data`, or at least the `PackReader()` code in `core/procs.go` and the entire `core/pack.go` module, with something "better".

This "better" thing would probably still "vet" the `core/data/linter*.joke` files (i.e. non-lib-defining Joker files), which `gen_data` currently does, at Joker build time. Better to find problems there than when actually trying to lint a file with the resulting Joker executable.

Beyond linting, the `gen_data` replacement could just create byte arrays representing the raw text of these source files, and the `core/pack.go` code (specifically, `UnpackHeader()` and `UnpackExpr()`) would be superseded by code that read a byte array just like any Joker file might be read at run time.

That means some startup time is spent parsing and evaluating expressions whenever linting is involved.

If that's deemed to expensive, or there is sufficient interest in speeding this up, this might be an opportunity to start in on a _Joker compiler_ for the limited forms in such files.

E.g. Go code could be compiled that, when called (dynamically) at run time, directly calls the internal code in Joker that Joker code such as `(declare foo)` would call anyway.

It would be interesting to work on this as a way of dipping one's toe in writing a Joker-to-Go compiler and to see whether any resulting improvement in startup time (when linting) could be measured.

**Comment by candid82** [comment]
I agree it makes sense to get rid of pack/unpack machinery to reduce complexity. However, going back to unprocessed source code doesn't make much sense to me. This is how Joker worked before I introduced pack/unpack. It makes Joker do considerably more work at start time. Granted linter files are not large and performance penalty may not be noticeable, but it's a penalty nevertheless, and I don't think simply reducing complexity justifies it in this case. After all, pack/unpack mechanism has worked remarkably well for a long time without causing any issues, so if we don't come up with something better we might as well leave it as is.
I was hoping to give linter files gen_code treatment, obviously with modifications to allow for dynamic execution, but keeping the serialization format (Go literals for the AST) the same. Not sure if it's feasible or even good idea. What do you think?

**Comment by jcburley** [comment]
> I agree it makes sense to get rid of pack/unpack machinery to reduce complexity. However, going back to unprocessed source code doesn't make much sense to me. This is how Joker worked before I introduced pack/unpack. It makes Joker do considerably more work at start time. Granted linter files are not large and performance penalty may not be noticeable, but it's a penalty nevertheless, and I don't think simply reducing complexity justifies it in this case. After all, pack/unpack mechanism has worked remarkably well for a long time without causing any issues, so if we don't come up with something better we might as well leave it as is.

That seems like the right call to me. It works, we'll likely know quickly if it ever breaks (probably because of changes to Joker internal objects or something), and we'll have time to fix or just replace it with a simple embedded-file-read mechanism.

> I was hoping to give linter files gen_code treatment, obviously with modifications to allow for dynamic execution, but keeping the serialization format (Go literals for the AST) the same. Not sure if it's feasible or even good idea. What do you think?

I'll look into this further and give it more thought.

**Comment by candid82** [comment]
"Actions express priorities". Let's just leave it as is.
