### ISSUE TITLE
Provide access to ioutil's TempDir and TempFile functions

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#367]
This would enable "safe" testing of `joker.bolt/open`, for example, versus hardcoding a single name (which could break when multiple tests go on at the same time in the same directory) or hacking up an equivalent to these functions.

These could go into `joker.os`.

Might as well add the `os.TempDir()` function too. But since this name conflicts with `ioutil.TempDir()`, perhaps the `ioutil` wrappers should go into a new `joker.ioutil` namespace.

A completely different approach might be to overload `joker.os/mkdir` and `joker.os/create` to accept a `:temp` keyword optionally specifying the directory (somehow) and treating the `name` argument as `prefix`.  (For `joker.os/mkdir`, `perm` could be made optional and be disallowed when `:temp` was specified, unless and until `ioutil.TempDir()` or equivalent supports such an argument?)

**Comment by jcburley** [comment]
(Or maybe just create `joker.os/mkdir-temp` and `joker.os/create-temp` to wrap these, keeping things simple yet discoverable?)

**Comment by candid82** [comment]
Addressed by https://github.com/candid82/joker/commit/f23ab8a0abc44649dcbc9fed9596f8cfccdfcbd8 (with the follow up renaming in https://github.com/candid82/joker/commit/8a26843b6cd98e5f83364589f5f00de2d1edd5ef)

I chose to put all three function in `joker.os`: `temp-dir`, `mkdir-temp`, and `create-temp`.

**Comment by jcburley** [comment]
Cool, thanks!!
