### ISSUE TITLE
sleep does not pause execution

### ISSUE THREAD

**Issue by benjyz** [candid82/joker#377]
I tried an example with sleep. expected result was a pause in execution

```
(println (joker.time/now))
(joker.time/sleep 100000)
(println (joker.time/now))
;example run
;2020-03-08 14:43:33.419187 +0700 +07 m=+0.066501528
;2020-03-08 14:43:33.419727 +0700 +07 m=+0.067040766
```

**Comment by candid82** [comment]
`joker.time/sleep`'s argument is expressed in nanoseconds. So your example sleeps for 100 microseconds. To sleep for 1 second: `(joker.time/sleep 1000000000)` or `(joker.time/sleep (* 1 joker.time/second))`
