### ISSUE TITLE
Stdin via pipe? 

### ISSUE THREAD

**Issue by martinklepsch** [candid82/joker#38]
I'm probably just missing something but the README mentions stdin support, shouldn't that mean the following should work?

```sh
cat boot/core/src/boot/cli.clj | joker --clojure --lint
```

Thanks! :)

**Comment by candid82** [comment]
Joker does support stdin, but you need to pass `--` as last argument (instead of file name). Also, `--clojure` is invalid argument, you probably want `--dialect clj`, or just rely on automatic dialect detection (based on file extension):
```
cat boot/core/src/boot/cli.clj | joker  --lint --
```

**Comment by martinklepsch** [comment]
Ooops, I thought I tried that but now tried again and it works 🙂 

I think the dialect might be required when linting from stdin as the joker process can't know the filename? 

Thanks! :)

**Comment by candid82** [comment]
Ah, that's right. `--dialect` is required when linting from stdin, unless you are OK with the default, which is `clj`.
