### ISSUE TITLE
Exiting REPL Via non-EOF Leaves Terminal Echo Off

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#384]
E.g. `(joker.os/exit 0)`.

At first blush, I'm guessing this is because `rl.Close()` (in `repl.go`), which is called via `defer` when returning from `repl()`, doesn't get called by `finish()` in `main.go`.

Not sure whether Joker should fix this, or `liner` should do whatever `readline` did to restore the terminal state even when `os.Exit()` was called.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/29c1970639b0e5c03af1dcdc78d2033cdec32266
