### ISSUE TITLE
Provide column start and end 

### ISSUE THREAD

**Issue by martinklepsch** [candid82/joker#39]
Currently joker provides the column where an error/warning "starts" but not where it ends. When an undeclared var is used or similar it would be useful to know start and end columns so the issue can be properly highlighted in editors.

**Comment by candid82** [comment]
I think most linters work this way: they only provide start line / column numbers. Editors are usually smart enough to underscore/highlight the entire word. Joker does actually track line / column of both start and end for each object, but doesn't expose it in error / warning messages. So it should be relatively easy to optionally add the end line / column to the output. There has to be, however, some justification for this feature. Can you point me to a linter that works this way?

**Comment by candid82** [comment]
Looks like there it not much interest in this feature. Closing for now.
