### ISSUE TITLE
Exiting with (exit) causes bash to misbehave

### ISSUE THREAD

**Issue by splayemu** [candid82/joker#391]
## Issue
Exiting with `(exit)` breaks the shell (bash). I am also using tmux if that makes a difference. Using Ctrl-D or Ctrl-C to exit works fine.

After exiting, every time I press enter, it doesn't create a new prompt and instead writes next to the current prompt.

```
octopus@octotop:~$ joker
Welcome to joker v0.15.1. Use '(exit)', EOF (Ctrl-D) or SIGINT (Ctrl-C) to exit.
user=> (exit)
octopus@octotop:~$ -bash: asdfiasdfasdf: command not found
octopus@octotop:~$ octopus@octotop:~$ octopus@octotop:~$
```

## Steps to reproduce:
1. run joker (v0.15.1)
2. type `(exit)` to quit
3. Type anything and notice bash misbehaving

## Environment:
Joker: v0.15.1
Linux: Debian GNU/Linux bullseye/sid
Bash w/ tmux

Let me know if you need any more information!

**Comment by jcburley** [comment]
I can repro this using Bash on Mac OS X (darwin).

WORKAROUND: `reset` (in Bash) to restore echoing.

It's a regression, in that introducing `liner` (to replace `readline`) caused this behavior in the first place, but I'm quite sure I confirmed https://github.com/candid82/joker/commit/29c1970639b0e5c03af1dcdc78d2033cdec32266 fixed it.

Maybe something broke it later?

**Comment by jcburley** [comment]
Oh, looks like `rl.Close()` got lost during https://github.com/candid82/joker/commit/e84b1d83356aee8cf3664075e474dd980486f44b.

**Comment by jcburley** [comment]
https://github.com/candid82/joker/pull/392 fixes this.

**Comment by candid82** [comment]
Ugh... Thanks @splayemu for reporting and @jcburley  for the proposed fix! It's a regression indeed and it doesn't help that I use fish that doesn't have this issue for whatever reason. I cut a new release with the fix.
