### ISSUE TITLE
Linter tests fail with 0.15.2

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#393]
E.g.:

```
FAILED: symbol-resolution-cljs
EXPECTED:

ACTUAL:
tests/linter/symbol-resolution-cljs/input.cljs:4:14: Parse error: Unable to resolve symbol: c
tests/linter/symbol-resolution-cljs/input.cljs:4:16: Parse error: Unable to resolve symbol: body
```

(Note that the commit for 0.15.2 is marked as failing the CI tests.)

**Comment by candid82** [comment]
Yeah, having a bad day. Accidentally included unfinished changes in the release. Fixed by https://github.com/candid82/joker/commit/b496b46e243df35117f09d8108baacf927cc5683
