### ISSUE TITLE
joker.os/env ignores the trailing value after equal (=) in env var

### ISSUE THREAD

**Issue by k2n** [candid82/joker#399]
Hi, 

My colleague noticed the trailing value after `=` in env var is ignored. Is it a bug?

```
$ TEST_ENV=foo bin/joker_0.15.3 -e '(-> (joker.os/env) (get "TEST_ENV") println)'
foo
$ TEST_ENV=foo= bin/joker_0.15.3 -e '(-> (joker.os/env) (get "TEST_ENV") println)'
foo
$ TEST_ENV=foo=bar bin/joker_0.15.3 -e '(-> (joker.os/env) (get "TEST_ENV") println)'
foo
```

Version: 0.15.3

Thanks,

**Comment by jcburley** [comment]
Indeed it is!

Fixed by https://github.com/candid82/joker/pull/400.

**Comment by jcburley** [comment]
WORKAROUND: `(-> (joker.os/get-env "TEST_ENV") println)`.

(The bug is in `joker.os/env`, which converts the entire environment to a map; while `joker.os/get-env` retrieves a single value from the environment, given the key.)

**Comment by candid82** [comment]
Thanks @k2n for reporting and @jcburley for the fix!
