### ISSUE TITLE
Implicit quoting of case statements not taken into account

### ISSUE THREAD

**Issue by martinklepsch** [candid82/joker#40]
<img width="391" alt="screen shot 2017-12-23 at 19 05 31" src="https://user-images.githubusercontent.com/97496/34321639-5b85041c-e814-11e7-932d-85100de1b5ea.png">

`case`'s left-hand arguments are always implicitly quoted and thus shouldn't be flagged here.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/cc5e26301cdc9896ab60a53001109230b8477840
