### ISSUE TITLE
http/send option to skip ssl verification for self-certification

### ISSUE THREAD

**Issue by quan-nh** [candid82/joker#401]
Do we have option to skip ssl verification for self-certification on `http/send` method?

Currently I got this error when sending request to a self signed host:
`Eval error: Post "https://..": x509: certificate signed by unknown authority`

**Comment by candid82** [comment]
No, this is not supported by Joker. The workaround is to shell out to `curl` with `(joker.os/sh "curl" ...)`

**Comment by quan-nh** [comment]
Thanks! Let's me try with `curl` shell..

**Comment by candid82** [comment]
Since this is rarely useful and there is a workaround with `curl` I am not going to implement this feature. If someone really wants it, PR is always welcome :)
