### ISSUE TITLE
Joker in WASM

### ISSUE THREAD

**Issue by roman01la** [candid82/joker#405]
Hey. Just so you know that Joker works in WASM. Had to patch bbolt and Go's WASM support is still missing IO, but you can run the CLI in eval mode just fine https://github.com/roman01la/joker

**Comment by candid82** [comment]
Wow, this is awesome! Can you provide brief instructions on how to try it out? I have not dealt with WASM before.

**Comment by roman01la** [comment]
@candid82 Build artifact is included in the forked repo, just run a web server from the root.

**Comment by candid82** [comment]
I get `CompileError: wasm validation error: at offset 43589: function body too big` when trying to load it.

**Comment by roman01la** [comment]
Somehow it does work for me, not always though. Maybe cleaning caches will help. The error is browser's validation of wasm files. For some reason they have this limit, but it also runs fine.

**Comment by candid82** [comment]
In what browser / OS does it work for you?

**Comment by roman01la** [comment]
Chrome on macOS, but as I said, it doesn't always run
