### ISSUE TITLE
joker.json/write-string doesn't understand lazy seqs [0.15.4]

### ISSUE THREAD

**Issue by hlship** [candid82/joker#406]
```
user=> (json/write-string [1 2 3])
"[1,2,3]"
user=> (json/write-string (vector (take 5 (iterate inc 100))))
"[\"(100 101 102 103 104)\"]"
user=> (json/write-string (vec (take 5 (iterate inc 100))))
"[100,101,102,103,104]"
user=> (json/write-string (list 6 7 8))
"\"(6 7 8)\""
```

When the value is sequential, but not a vector, json/write-string emits a single value, the string-representation of the entire list.

It should emit a JSON array of the values in the seq.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/075e90d6e98537acff1e9f539fc6f9148f432a5f
