### ISSUE TITLE
Incorrect warning about redundant do in anonymous function [0.15.5]

### ISSUE THREAD

**Issue by mainej** [candid82/joker#412]
This code is marked as having a redundant `do`, which is incorrect:

```clojure
#(do (a x) (b y))
```

There are anonymous functions where the do would be redundant:

```clojure
#(do (a x)) ;; could be `#(a x)`
```

There was another bug recently about a redundant do, #407. The linter seems to generate this warning based on how and where the `do` was generated. But shouldn't it care also (or instead) about whether the `do` wraps one expression (making it redundant) or many expressions (not redundant). Just a thought—I don't know the code internals well enough to say whether this is the right direction.

**Comment by candid82** [comment]
This is fixed in v0.15.6.
