### ISSUE TITLE
How to use Joker with fiber

### ISSUE THREAD

**Issue by gsrai** [candid82/joker#413]
Hi, this isn't an issue but i couldn't find the docs and didn't know where the best place to ask something like this.
Are there any examples of how to use joker with existing libraries in go, like a webapp using fiber?
I want to create a backend using postgres + gorm + fiber + graphql.

thanks

**Comment by jcburley** [comment]
Joker doesn't currently offer a way to automagically wrap arbitrary Go libraries (though my experimental [gostd fork](https://github.com/jcburley/joker/blob/gostd/GOSTD.md) is a baby step in that direction).

Nor does it support the Go `plugin` package.

So, to add support for a Go library, one must change Joker itself (and rebuild it) to yield a custom Joker executable with the desired support.

For information on how to do that, please see:

https://github.com/candid82/joker/blob/master/DEVELOPER.md

**Comment by gsrai** [comment]
Ah cool, thanks 👍
