### ISSUE TITLE
"SIGILL: illegal instruction" errors related to 'go'

### ISSUE THREAD

**Issue by SolidStill** [candid82/joker#415]
Hello, and, first of all, thanks to the creator and all the contributors.

Specs + Installation Info:
- I'm running macOS Mojave on older (officially unsupported) hardware by using "macOS Patcher" distributed by "dosdude1
- joker is installed via the Homebrew package manager, and forcing the "build from source" method: "brew install -s joker"
- I have encountered similar "go"-related errors previously but the current distributions of of "go" have addressed these issues - my current installed version of go is "go1.14.5 darwin/amd64"

I'm encountering consistent runtime errors, but if I do a reinstall of joker via "brew reinstall -s joker" I find that joker behaves as expected, without error warnings, for a short period of time - I have no idea what is triggering the lapse back into unexpected behaviour.

These are the Illegal Instruction errors shown at runtime:
```
SIGILL: illegal instruction
PC=0x10696a0 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00004cf20 sp=0xc00004cf18 pc=0x10696a0
net.init()
	/usr/local/Cellar/go/1.14/libexec/src/net/dnsclient_unix.go:36 fp=0xc00004cf28 sp=0xc00004cf20 pc=0x1114ee0
runtime.doInit(0x1a099a0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc00004cf58 sp=0xc00004cf28 pc=0x10447ba
runtime.doInit(0x1a0bee0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00004cf88 sp=0xc00004cf58 pc=0x1044787
runtime.main()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc00004cfe0 sp=0xc00004cf88 pc=0x1037bbe
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00004cfe8 sp=0xc00004cfe0 pc=0x1067e31

rax    0x9ce589485577f8c5
rbx    0x12
rcx    0x0
rdx    0x1a09a30
rdi    0xc0000a6458
rsi    0x1114ee0
rbp    0xc00004cf48
rsp    0xc00004cf18
r8     0x4
r9     0x4
r10    0x6
r11    0xc0000a63f0
r12    0x4
r13    0xc0000ba118
r14    0x8
r15    0xc0000a62d0
rip    0x10696a0
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
```

The weird thing I notice is that the directories mentioned at the beginning of the error output don't exist - I have no "/usr/local/Cellar/go/1.14" directory. Also, my current go version is not 1.14, it's 1.14.5, and as such "/usr/local/Cellar/go/1.14.5" **does** exist.

Any ideas anyone? Thanks very much.

**Comment by candid82** [comment]
Joker Homebrew package doesn't support installation from the source. Can you try [building](https://github.com/candid82/joker#building) Joker manually?

**Comment by SolidStill** [comment]
I'll give it a go, thanks for letting me know 👍
