### ISSUE TITLE
Suggest stripping version from release artifacts

### ISSUE THREAD

**Issue by tonymcneil** [candid82/joker#425]
This is just a suggestion as a nice to have so that users can always easily download the latest version of this nice lib programmatically, you could remove the version number from the various download artifact names.

e.g. the following:
- joker-0.15.7-linux-amd64.zip
- joker-0.15.7-mac-amd64.zip
- joker-0.15.7-win-amd64.zip

become:
- joker-linux-amd64.zip
- joker-mac-amd64.zip
- joker-win-amd64.zip

Therefore the following url pattern can be used: https://github.com/user/repo/releases/latest/download/foo.zip
see: https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-2845270
 
e.g. Download for the latest linux release would become: https://github.com/candid82/joker/releases/latest/download/joker-linux-amd64.zip

**Comment by candid82** [comment]
This makes sense. I'll strip the version from the release file names in the next release. Thank you for the suggestion!

**Comment by candid82** [comment]
Done in Joker v1.0.1.
