### ISSUE TITLE
Macros that expand to functions in JVM Clojure don't expand to functions in Joker

### ISSUE THREAD

**Issue by Zabolekar** [candid82/joker#426]
First of all, thank you for this implementation.

Now, the issue.

The following macro produces a function in JVM Clojure but not in Joker:
```
user=> (defmacro make-fn [] (fn [] nil))
#'user/make-fn
user=> (macroexpand '(make-fn))
#object[Fn]
user=> (make-fn)
<file>:0:0: Parse error: Cannot parse form: #object[Fn]
```

`(defmacro make-fn [] '(fn [] nil))` (note the quote) works in both.

Joker version: v0.15.6
Platform: x86_64 GNU/Linux

**Comment by candid82** [comment]
@Zabolekar Thanks for reporting! This is fixed by https://github.com/candid82/joker/commit/b31e761a129c1a85ac2d265f8390743527fbf75f.
