### ISSUE TITLE
Build a single binary

### ISSUE THREAD

**Issue by rosineygp** [candid82/joker#428]
Hi!

There's a way to build a single binary including my code?

Even in hardmode like build full joker code putting my code in a specific location, or something like this.

**Comment by jcburley** [comment]
Joker does not (yet) support a simple "drop-in" mechanism for building with arbitrary code.

But it does provide two ways to add custom Joker (and Go) code, as long as certain rules are followed.

In short; if your code has logic (that is, ordinary "code") expressed in Joker code, it would need to be built in as a "core" namespace.

Else, if it's just defining wrappers around Go code, it would be built in as a "standard-library-wrapping (std)" namespace.

See the [`LIBRARIES.md`](../blob/master/LIBRARIES.md) and [`DEVELOPER.md`](../blob/master/DEVELOPER.md) files for more info (and read them thoroughly before proceeding).

And please keep in mind that the documentation is surely incomplete; it might be leaving something important out! But let us know if you run into some such thing (and feel free to submit a PR).
