### ISSUE TITLE
Support Bracketed Paste

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#429]
I just learned about this:

https://cirw.in/blog/bracketed-paste

(I was wondering why my pastes into a terminal session were resulting in extra escape sequences, and discovered this new-ish feature.)

Might be nice for Joker to support this, although it could be totally a `liner` thing...?

(And, yes, I'm volunteering to do it, if desired.)

**Comment by candid82** [comment]
Looks useful and I don't see downsides in supporting this. I *think* it should be implemented in `liner`, but not 100% sure.

**Comment by candid82** [comment]
Moved to liner: https://github.com/candid82/liner/issues/4
