### ISSUE TITLE
Interpret all def* forms as known macros

### ISSUE THREAD

**Issue by martinklepsch** [candid82/joker#43]
Probably not ideal as a default but given that `def*` macros is a very common thing it could be nice.

Just a thought, just close if you think this is a bad idea :)

**Comment by candid82** [comment]
I had similar thoughts in the past but in the end decided not to complicate things with custom rules like this. In my experience it's not that hard to add all `def*` macros to `.joker` file one by one.

**Comment by candid82** [comment]
`:known-macros` could support regular expressions, but again, I am not sure if it's worth the effort and additional complexity. Closing for now.
