### ISSUE TITLE
Wrong format result.

### ISSUE THREAD

**Issue by glyh** [candid82/joker#434]
I use joker to format my clojure code. 

When I have some small double values, say 1e-7, the formatter just output 0.0.

This would cause some fault on Clojure Codes, please fix it.

**Comment by jcburley** [comment]
I'm thinking this is more than a formatting issue:

```
$ joker
Welcome to joker v0.15.7. Use '(exit)', EOF (Ctrl-D), or SIGINT (Ctrl-C) to exit.
user=> (println 1e-9)
0.0
nil
user=> (println 1e-7)
0.0
nil
user=> (println 1e-5)
0.00001
nil
user=> ^D
$
```

Gonna take a quick look at the code myself, in case something obvious pops out.

**Comment by jcburley** [comment]
More likely a printing than a reading issue:

```
user=> (< 1e-9 1e-7)
true
user=> (< 1e-9 1e-9)
false
user=> (< 1e-9 1e-11)
false
user=> 
```

**Comment by jcburley** [comment]
Also, 1.9999999 renders as "2.0", but is stored such that it compares as less than 2.0.

**Comment by jcburley** [comment]
I've got a fix ready for a PR, just adding tests.
