### ISSUE TITLE
Tagged literals can cause read error even if hidden behind reader conditional

### ISSUE THREAD

**Issue by Zabolekar** [candid82/joker#446]
Joker version: 0.15.7.

Minimal example:

```clojure
#?(:broken #a "123" :default 456)
```

Output in Joker:

```
<repl>:1:13: Read error: No reader function for tag a
```

ClojureScript and JVM Clojure both output `456`.

As a more practical example, the following snippet can't be read in Joker:

```clojure
#?(:joker (joker.time/parse "2006-01-02" "2021-06-21") :clj #inst "2021-06-21")
```

**Comment by candid82** [comment]
Thanks for reporting! Fixed by https://github.com/candid82/joker/commit/a3e2e3d24c0057d5aa39f229ef7c3408541f9bd9
