### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jcsims** [candid82/joker#45]
Not an issue per se, but just wanted to say thanks for writing such a useful tool! I use it everyday at work, and it helps me tremendously 💯

**Comment by candid82** [comment]
Thank you for the kind words! I am glad you find the tool useful.

**Comment by blak3mill3r** [comment]
Joker is a _significant_ upgrade to my Clojure experience. Within an hour of trying it I had committed it to my emacs config, where it will remain. Mad props... we really needed something like this. I'm looking forward to seeing it evolve, and I've been sharing it with every Clojure user I know.

**Comment by candid82** [comment]
Thanks @blak3mill3r!

**Comment by borkdude** [comment]
@candid82 If you decide to apply for Clojurists Together, I'll definitely vote for your tool.

See: https://twitter.com/cljtogether/status/974193498680262656

**Comment by candid82** [comment]
@borkdude Thanks, I really appreciate your support! I think I am not ready for this kind of commitment, but maybe in the future...
