### ISSUE TITLE
Joker Allows Shadowing Builtin Types

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#455]
At least when linting, if not generally, Joker should probably behave as does Clojure here:

```
$ clojure -M -e '(def String "hey")'
Syntax error compiling def at (REPL:1:1).
Expecting var, but String is mapped to class java.lang.String

Full report at:
/var/folders/m_/0sxkm11s5wd625ypnp0g0ffm0000gn/T/clojure-5069748075906968797.edn
$ joker -e '(def String "hey")'
#'user/String
$ joker --lint - <<< '(def String "hey")'
$
```

**Comment by candid82** [comment]
Addressed by https://github.com/candid82/joker/commit/cb2af8107ca2b3ee9eb254f36b75a9dece120b17 I chose to keep Joker's runtime behavior as is. ClojureScript allows type names in `def` too.
