### ISSUE TITLE
Recognize swap-vals! and reset-vals!

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#46]
<img width="544" alt="screenshot 2018-01-18 09 25 27" src="https://user-images.githubusercontent.com/284934/35087754-9e2d861e-fc31-11e7-9f72-bf38008c4b86.png">

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/2e60e8044b5039a10b430df44588dc3801a09076
