### ISSUE TITLE
Support Arbitrary BigFloat Precision for stdlib Packages and "M"-Suffixed Constants

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#460]
Add `MakeBigFloat` API (to `core`) so stdlib packages can specify `^BigFloat` (for definitions of constants); also support arbitrary precision (based on number and widths of mantissa digits) for such constants (ending in `M`), instead of setting precision to a constant 256 as Joker currently does.

This work is already done in https://github.com/jcburley/joker/releases/tag/gostd-v0.10: it computes the precision of a `BigFloat` constant based on the number and “width” of digits in the constant (minimum being `53`, the precision for a `float64` aka `Double`); and a new core function `precision` returns the precision info.

I’m volunteering to crossport this over here and also to create a `set-precision` function that’d work on BigFloat if there’s any interest.

(I think there might be more work that could be done to preserve/extend precision on operations involving `BigFloat`; this seems like an especially useful starting point, at least.)

**Comment by candid82** [comment]
Frankly I doubt many people use `BigFloat`, but having a better support for it would not hurt. The improvements you described make sense to me.

**Comment by jcburley** [comment]
> Frankly I doubt many people use `BigFloat`, but having a better support for it would not hurt. The improvements you described make sense to me.

Okay, I'll work up a PR to bring that support over sometime soon!
