### ISSUE TITLE
Piping standard input to starting subprocesses

### ISSUE THREAD

**Issue by hlship** [candid82/joker#461]
On of my use cases for Joker involves building a processing pipeline:
- Capture a JSON response with curl
- Pass it through jq to pare it down a little (https://stedolan.github.io/jq/)
- Pass that through gron to make it grepable (https://github.com/tomnomnom/gron)
- Pass that through fzf for interactiive searching (https://github.com/junegunn/fzf)

What I'm seeing when using either joker.os/sh or joker.os/exec is that the final step, fzf, doesn't run correctly; it runs "blind" rather than bringing up its text-mode UI.

```
joker -e '(joker.os/sh "sh" "-c" "ls -l | fzf")'
```

You can use the arrow keys to move an invisible cursor, and the tab key to select lines, and enter to exit fzf, but you don't get to see any visual feedback:

```
~/workspaces/walmart/cph-tools > joker -e '(joker.os/sh "sh" "-c" "ls -l | fzf")'
{:success true, :exit 0, :out "-rw-r--r--  1 hship  staff  4112 Mar 31 15:49 common.joke\n", :err ""}[
```

My operating theory is that Joker has wrapped stdin and/or stdout in such a way that fzf can't operate.

I would suggest that a new function be added to joker.os that would, essentially, replace the running Joker process with a new process, and ensure that stdin/stdout are restored properly.

I would imagine it could look like this:

```
(joker.os/launch "ls -l | fzf")
```

Alternately, this `launch` function could, if possible, return a proc map, like `joker.os/exec`.  Either would work for my purposes.

Essentially, I would like building and executing shell pipelines in Joker to be as easy as, or easier than, doing the same in Bash.

**Comment by candid82** [comment]
@hlship This is already possible with `joker.os/exec`, but you have to explicitly connect stdin, stdout and stderr:
```
(joker.os/exec "fzf" {:stdin *in* :stdout *out* :stderr *err*})
```
or 
```
(joker.os/exec "sh" {:args ["-c" "ls -l | fzf"] :stdin *in* :stdout *out* :stderr *err*})
```
Does this achieve what you want?

**Comment by hlship** [comment]
That does work (fzf executes normally).
