### ISSUE TITLE
Embedded Joker

### ISSUE THREAD

**Issue by base698** [candid82/joker#466]
@candid82 Was wondering about importing joker to use as a clojure DSL.  I just started by trying to use `core.TryReader()` but I get a lot of fail to import `TYPE` errors.  

Example:
```
../go-workspace/pkg/mod/github.com/candid82/joker@v0.15.6/core/channel.go:36:9: undefined: TYPE
../go-workspace/pkg/mod/github.com/candid82/joker@v0.15.6/core/data.go:24:14: undefined: linter_allData
```

Any ideas?  Is there some code generator I'd have to run first?

**Comment by jcburley** [comment]
Check the `run.sh` script (it does `go generate ./...`), and also review `DEVELOPER.md`, especially references to `gen_code`, a code generator for the "final" version of the Joker executable.

If `gen_code` isn't being run by your build process, that could explain what you're seeing.

**Comment by base698** [comment]
I'm including it as an import.  The imports in `$GOPATH/pkg` and run don't seem to work.  I can run it from the directory.  

Had to do this: `go mod edit -replace=github.com/candid82/joker=../joker` for reference.

**Comment by base698** [comment]
Thanks!
