### ISSUE TITLE
format overwrite

### ISSUE THREAD

**Issue by benjyz** [candid82/joker#469]
I would like to format a file in place so instead of

`joker --format foo.edn > foo_new.edn`

do

`joker --format --overwrite foo.edn`

 analogous to gofmt. 

wip here: https://github.com/benjyz/joker/commit/90537796735af164c85bdaad83f4d42733e6341a

**Comment by candid82** [comment]
I wrote a [specialized formatter](https://github.com/candid82/cljf/) that already supports formatting in place. It's also much smaller and faster than Joker's format mode, so I don't think it makes a lot of sense to extend Joker's format mode. I will accept a PR though. Closing for now.
