### ISSUE TITLE
Strange lint warning in `case` forms 

### ISSUE THREAD

**Issue by iafilatov** [candid82/joker#47]
```clojure
(case val
  ("F" "f") false    ;; Parse warning: F is not a function
  true)

(case val
  ("F" "f") "false"  ;; ok
  true)

(case val
  ("T" "t") true     ;; ok
  false)
```

v0.8.9. I think this appeared in one of the recent versions, not sure in which.

Looks like github's syntax hl has the same problem :smile:

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/80fa9fef5123b1dc6c38c42d2fb0a4656faf778e
