### ISSUE TITLE
disable auto-complete in REPL

### ISSUE THREAD

**Issue by lsh-0** [candid82/joker#471]
Is it possible to disable the auto-complete behaviour for brackets and quotes in the REPL? 

It's very frustrating and not helpful.

**Comment by candid82** [comment]
`joker --no-readline` will disable auto-complete, as well as all readline features. You can use `rlwrap` instead: `rlwrap joker --no-readline`. This will give you readline features but without the auto-comlete.

**Comment by lsh-0** [comment]
`rlwrap joker --no-readline` works a treat, thank you.
