### ISSUE TITLE
`pprint` to file

### ISSUE THREAD

**Issue by kovasap** [candid82/joker#478]
I'm using joker to generate a large edn data structure, which I want my script to write to a file directly (not print to standard output). Is there a way for `pprint` to simply give me a string or write to a file instead of to stdout?

Right now I'm just `spit`ing the edn string directly into a file, which puts it all on one line : /.

**Comment by candid82** [comment]
```
(def data {:foo "bar"})

;; to a string
(with-out-str
  (pprint data))

;; to a file
(let [out (joker.os/create "filename")]
  (binding [*out* out]
    (pprint data))
  (joker.os/close out))
```

**Comment by kovasap** [comment]
That works thanks!
