### ISSUE TITLE
Strings in :require

### ISSUE THREAD

**Issue by jacekschae** [candid82/joker#48]
I'm playing quite a bit with [shadow-cljs](https://github.com/thheller/shadow-cljs) and the way it works with npm is that instead of using symbols in `:require` it uses strings.

Example:

```clojure
(ns app.fb-auth
  (:require ["firebase" :as firebase]
            [clojure.string :as string]
            [app.state :as state]))
```

which gives following error
<img width="859" alt="screen shot 2018-03-02 at 04 27 13" src="https://user-images.githubusercontent.com/31179812/36882212-b73bdf4e-1dd2-11e8-8284-e0a6c5219800.png">

is there anything I could do about this?

Thank you

**Comment by candid82** [comment]
Fixed by b10110c3464f6699a47a66dcb8f85aa24a64bacf and 49036cc6e569131c4568719347c6be3f88d7347a

**Comment by releve** [comment]
Thank you! I look forward to the next release.

**Comment by jacekschae** [comment]
Thank you!

Look forward to the next release
