### ISSUE TITLE
Invalid use of / in symbol name

### ISSUE THREAD

**Issue by txgruppi** [candid82/joker#483]
Sorry if this is not an issue, I'm new to lisp.

I have this source code:

```lisp
(var t 0)
(var x 96)
(var y 24)

(fn _G.TIC []
  (when (btn 0) (set y (- y 1)))
  (when (btn 1) (set y (+ y 1)))
  (when (btn 2) (set x (- x 1)))
  (when (btn 3) (set x (+ x 1)))
  (cls 0)
  (spr (+ 1 (* (// (% t 60) 30) 2))
       x y 14 3 0 0 2 2)
  (print "HELLO WORLD!" 84 84)
  (set t (+ t 1)))
```

and when I run `joker --format colorsort.fnl` I get the following error:

```
colorsort.fnl:11:19: Read error: Invalid use of / in symbol name
```

Can't `//` be allowed as a symbol name?

**Comment by candid82** [comment]
This doesn't look like Clojure code. Is this some other Lisp-like language? Joker doesn't format any Lisp code, only Clojure specifically.
You may want to find a formatter for this language specifically. You can also try https://github.com/candid82/cljf, which is also a Clojure formatter but with more permissive reader that may work for your language.

**Comment by txgruppi** [comment]
Thank you!
