### ISSUE TITLE
Surrounding text with parens in the REPL

### ISSUE THREAD

**Issue by dbohdan** [candid82/joker#485]
Suppose I have the REPL prompt in this state:

```
user=> foo
```

How do I go to the following state without first deleting `foo` and then typing it again?

```
user=> (foo)
```

Typing `(` adds a matched pair of parentheses. You can't delete just one.

```
user=> ()foo
user=> f()oo
user=> foo()
```

**Comment by candid82** [comment]
Type `(`, which adds `()`. Then delete `)` with delete key. It's `Ctrl+D` on MacOs, but should work everywhere as long as you have delete key (not backspace, which won't delete parenthesis).
If you find this annoying, you can opt out with `joker --no-readline`, but this will disable pretty much all editing features. However, you can wrap it with lrwrap: `rlwrap joker --no-readline`. This gives you line editing but without auto-parens behavior.

**Comment by dbohdan** [comment]
Thanks! Ctrl+D works. I am not on a Mac, but my primary keyboard has no Delete key, and I didn't think to try it. (It may help other users if there is a note about this in the readme.)

**Comment by candid82** [comment]
I've added a note about this [here](https://github.com/candid82/joker#usage).

**Comment by dbohdan** [comment]
> If you find default REPL editing behavior annoying (e.g. automatic parenthesis matching, backspace doesn't delete a matching parenthesis), try [...]

This fragment needs s/doesn't delete/deletes/. I would explicitly say that Delete gets around parentheses matching.

**Comment by candid82** [comment]
> This fragment needs s/doesn't delete/deletes/. 

Well, backspace won't delete parentheses unless you are deleting an open parenthesis immediately followed by a close parenthesis. That's what I meant in that fragment.

**Comment by dbohdan** [comment]
I understand your intent, but the current phrasing is ambiguous. It seems to suggest the user should try `joker --no-readline` to _enable_ a mechanism for deleting a matching parenthesis with the parenthesis they are deleting with backspace. I'd be confused by it if I hadn't used Joker.

I'd write something like this:

> Hint: In the REPL typing `(` adds a pair of matched parentheses. Use the delete key to remove individual parenthesis ignoring parenthesis matching. Ctrl-D also works as a delete key on some systems. If you find the default REPL editing behavior annoying (e.g., automatic parenthesis matching, backspace doesn't delete individual parenthesis), try `joker --no-readline` or `rlwrap joker --no-readline` if you have [rlwrap](https://github.com/hanslub42/rlwrap) installed.
