### ISSUE TITLE
a_linter_all_data.go contains non-determinism

### ISSUE THREAD

**Issue by bmwiedemann** [candid82/joker#491]
While working on reproducible builds for openSUSE, I found that our `joker` package produced a different binary in every build. My guess is that this comes from variations in `a_linter_all_data.go` and 4 other `a_linter_*_data.go` files.
This is produced by `go run -tags gen_code gen_code/gen_code.go` and probably has variations from random go map iteration order.

**Comment by brejoc** [comment]
Looks like you are right about that: https://go.dev/blog/maps#iteration-order

**Comment by bmwiedemann** [comment]
Are there plans to fix this? I'm not a go expert...

**Comment by candid82** [comment]
@bmwiedemann should be fixed now.

**Comment by bmwiedemann** [comment]
Confirmed. Commit d2817bb18cd9cc0274460113a97dc87f2613d1ad indeed makes build results deterministic in my tests.
