### ISSUE TITLE
`joker.json/write-string` encodes an empty array as null

### ISSUE THREAD

**Issue by NuclearKev** [candid82/joker#497]
The title pretty much explains it but if you run: 
```
user=> (joker.json/write-string {"hours" []})
"{\"hours\":null}"
```

I believe this should evaluate to: `"{\"hours\": []}"`

**Comment by eko234** [comment]
same issue here :P

**Comment by eko234** [comment]
Mmmm I was checking the code and the fix is real simple, if you are building it from source change the line 39 at std/json/json-native.go to:  var res []interface{} = []interface{}{}, I'll make a pr tho.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/pull/498
