### ISSUE TITLE
Reading a fixed number of bytes from *in*

### ISSUE THREAD

**Issue by dbohdan** [candid82/joker#504]
Is there a way to read no more than a certain fixed number of bytes from `*in*` (or an `IOReader` in general)? I didn't find a function for it in `joker.io`.

In order to comply with the [CGI spec](https://datatracker.ietf.org/doc/html/rfc3875), my guestbook must not read from standard input more than the number of bytes given in the `CONTENT_LENGTH` environment variable. I thought this wasn't a problem in practice because CGI servers closed your program's standard input. You could read until EOF, and `(slurp *in*)` worked. However, I have run into the guestbook hanging with [Weborf](https://ltworf.codeberg.page/weborf/). That it ignores `CONTENT_LENGTH` seems to be the cause.

If there is currently no way to read up to a fixed number of bytes, please implement one.

Edit: Reading a fixed number of bytes can result in invalid UTF-8. I think it is okay if reading the rest of the input and joining the two strings together doesn't fix it and there is no way to fix it.

**Comment by candid82** [comment]
@dbohdan I've added `joker.io/read` function [here](https://github.com/candid82/joker/commit/4c8821c5cce60cc59a770888bb6a6c29f0e733ba) Here is an example of reading a file:
```
(let [f (joker.os/open "repl.go")]
  (loop [s (joker.io/read f 100)]
    (when-not (= "" s)
      (print s)
      (recur (joker.io/read f 100)))))
```

Can you give it a try and see if it works for your use case?

**Comment by dbohdan** [comment]
Yep, I works. Replacing `slurp` with `joker.io/read` in https://github.com/dbohdan/joker-cgi-guestbook/commit/277ca16aa0834eba6af5de6f7bb40f5b940eadab has fixed the hang on Weborf. I think this is solved. Thanks!
