### ISSUE TITLE
joker.base64/decode-string can't decode anything greater than or less than 160 characters

### ISSUE THREAD

**Issue by NuclearKev** [candid82/joker#505]
Say you have a JWT and you want to parse the base64 in the middle of it. Here is the example basey64:
```
"eyJhdWQiOiJhZG1pbiIsImV4cCI6MS43MjAxMDEwMjExNTQ0MjQ4MjllOSwiaWF0IjoxLjcyMDAxNDYyMTE1NDQyNDgyOWU5LCJpc3MiOiJza2VkLWF1dGgiLCJ1c2VyIjozODMsInVzZXJUeXBlIjoiQWRtaW4ifQ"
```
If you attempt to decode it with joker.base64/decode-string, you'll get the following error:
```
Eval error: Invalid base64 string: illegal base64 data at input byte 160
```
The data inside contains this:
```
{"aud":"admin","exp":1.720101021154424829e9,"iat":1.720014621154424829e9,"iss":"sked-auth","user":383,"userType":"Admin"}
```
I'm not sure if this is something weird with how the JWT was made or if this is a bug with joker.

EDIT: I hit the post button before I finished...

**Comment by dbohdan** [comment]
The length of a base64-encoded message must be divisible by four. When it isn't, you must append `=` characters as padding.

The example you give is 162 characters long and doesn't have the padding. I don't know if this is standard for JWT. You can add the padding with a function like this:

```clojure
(defn pad-base64 [s]
  (str s (case (rem (count s) 4)
           0 ""
           ; 1 should never occur.
           2 "=="
           3 "=")))
```

Apply `pad-base64` then `joker.base64/decode-string`.

**Comment by candid82** [comment]
@dbohdan Thank you for looking into this!

**Comment by dbohdan** [comment]
@candid82 You're welcome!

**Comment by NuclearKev** [comment]
> The length of a base64-encoded message must be divisible by four. When it isn't, you must append `=` characters as padding.
> 
> The example you give is 162 characters long and doesn't have the padding. I don't know if this is standard for JWT. You can add the padding with a function like this:
> 
> ```clojure
> (defn pad-base64 [s]
>   (str s (case (rem (count s) 4)
>            0 ""
>            ; 1 should never occur.
>            2 "=="
>            3 "=")))
> ```
> 
> Apply `pad-base64` then `joker.base64/decode-string`.

🤦 I should have known this... In fact, I've implemented this exact thing in a clojurescript app using JWT. Sorry for opening this issue without probable cause!
