### ISSUE TITLE
#'joker.core/get conflict

### ISSUE THREAD

**Issue by adamneilson** [candid82/joker#53]
In `(ns some.place)` I have a function 

```clojure
(defn get [options] 
   (do-something))
```

I get the following warning (in NeoVim):

`WARNING: get already refers to: #'joker.core/get in namespace user, being replaced by: #'user/get`

Does anyone know if there's a workaround for this?

**Comment by candid82** [comment]
Joker issues a warning on name collisions with core functions, similarly to Clojure  proper. (try typing `(defn get [])` in Clojure repl). I generally find this warning useful, but perhaps it could be put behind a config flag...

**Comment by adamneilson** [comment]
Oh I see, now I get it. Thanks for the clarification. 

Also while I'm at it, thanks for writing this! It's so useful!
