### ISSUE TITLE
Cannot get :ignore-unused-namespaces to work

### ISSUE THREAD

**Issue by wasamasa** [candid82/joker#56]
Suppose I have `test.clj`:

```clojure
(ns foo.core
  (:require [bar.baz]))
```

This gives me a warning, "unused namespace bar.baz". I'm assuming the following configuration in `.joker` would inhibit it, but no luck:

```clojure
{:ignore-unused-namespaces [bar.baz]}
```

Other configuration options like `known-macros` work as expected.  It makes no difference whether I'm linting Clojure or ClojureScript files.  I'm using v0.9.1 on Arch Linux.

**Comment by candid82** [comment]
It's `ignored-unused-namespaces`, not `ignore-unused-namespaces`.

**Comment by wasamasa** [comment]
You're absolutely right, thanks!
