### ISSUE TITLE
Support ClojureScript-specific interop

### ISSUE THREAD

**Issue by wasamasa** [candid82/joker#57]
http://cljs.github.io/api/syntax/dot

This allows doing things otherwise not allowed in Clojure. Examples are `e.target.value` (accessing a property of a variable), `Math.PI` (accessing a property of an imported object), `(XHR.send ...)` (calling a property belonging to an imported object).  I've taken a brief look at the code, but haven't found CLJS-specific code for interop, so I suspect both Clojure and ClojureScript are treated the same.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/830f4f0e48618baae1989425c6ec7b286a7410ed

**Comment by wasamasa** [comment]
Thank you, this is a great improvement! There's one case not caught yet though:

```clojure
(ns foo.bar
  (:import goog.net.XhrIo))

(XhrIo.send "http://example.com" (constantly nil))
```

`XhrIo` is highlighted here, with "Parse error: Unable to resolve symbol: XhrIo".

**Comment by candid82** [comment]
Ah, right. Should be good now: https://github.com/candid82/joker/commit/8eade6f4ebe8fea62c2d51e458d6ead255775ae4
