### ISSUE TITLE
"undefined" errors

### ISSUE THREAD

**Issue by kuwze** [candid82/joker#58]
Upon running:

>  $ go get github.com/candid82/joker

I get:

> github.com/candid82/joker/core
> go/src/github.com/candid82/joker/core/procs.go:1594:28: undefined: linter_allData
> go/src/github.com/candid82/joker/core/procs.go:1600:27: undefined: linter_cljxData
> go/src/github.com/candid82/joker/core/procs.go:1604:28: undefined: linter_cljData
> go/src/github.com/candid82/joker/core/procs.go:1606:28: undefined: linter_cljsData
> go/src/github.com/candid82/joker/core/procs.go:1805:14: undefined: coreData
> go/src/github.com/candid82/joker/core/procs.go:1806:14: undefined: timeData
> go/src/github.com/candid82/joker/core/procs.go:1807:14: undefined: mathData

Also I was able to install the binary from the download page successfully and installed the Emacs library flycheck-joker and it works awesomely! Just wanted to thank you for writing such a cool project.

Another question: does this library suffer from flycheck-clojure's issue:

> Do not use squiggly-clojure unless your code can be reloaded without side effects, as the linters will be reloading it repeatedly.

**Comment by candid82** [comment]
As pointed out in [build instructions](https://github.com/candid82/joker#building) it should be OK to ignore those "undefined" messages. I have not tested those instructions in a while, so please let me know if they don't work.

As for reloading issue, Joker linter does not actually load/execute your code, so it doesn't matter what the code does.

**Comment by candid82** [comment]
I tested build instructions and the do seem to work. Closing this issue, but let me know if you still have problems building Joker.
