### ISSUE TITLE
Unused bindings via :as

### ISSUE THREAD

**Issue by lbradstreet** [candid82/joker#59]
I may be alone in this request, but I often like to use `:as` in destructuring to name a map for descriptive purposes, even though I don't use the binding. Is it possible to ignore measurement here?

e.g.
```
(defn my-fn [{:keys [value] :as measurement}]
   value)
```

Thank you for this tool. It has already improved my life massively when used via vim.

**Comment by candid82** [comment]
Implemented in https://github.com/candid82/joker/commit/c87d223476313a384c46fd13bce8e72fdd5e5eb3
You can now disable warnings on unused `:as` bindings by adding the following to your .joker file:
```clojure
{:rules {:unused-as false}}
```

**Comment by lbradstreet** [comment]
Awesome! Thank you again for a great tool.
