### ISSUE TITLE
Clojure 1.9 namespaced destructuring

### ISSUE THREAD

**Issue by julienfantin** [candid82/joker#6]
Clojure 1.9 allows the following:

```
(require '[com.acme.foo :as foo])
(let [{::foo/keys [bar]} {:com.acme.foo/bar :YUP}]
  bar)
;; => :YUP
```

But joker signals an `Unable to resolve symbol: bar` error.

**Comment by candid82** [comment]
Thanks for reporting! I have not looked into 1.9 support yet (there is enough unimplemented features from 1.8 to keep me busy), but I'll see how much work it would be to add this particular one.

**Comment by candid82** [comment]
Fix by https://github.com/candid82/joker/commit/eee6a14ac57c9216b6191a90d1ec59c5180aa381
