### ISSUE TITLE
Unable to resolve symbol

### ISSUE THREAD

**Issue by kuwze** [candid82/joker#60]
I am currently getting the error `"Unable to resolve symbol: blah"` a lot and I am not sure what to do.

Here is a picture of my code; all of the errors being highlighted are of the type "`Unable to resolve symbol: ..."`:
![screenshot from 2018-05-14 15-35-45](https://user-images.githubusercontent.com/31353255/40019465-519eaa3c-578d-11e8-9599-111ccb8b47e1.png)

**Comment by borkdude** [comment]
@kuwze Have you tried this? https://github.com/candid82/joker#reducing-false-positives

**Comment by kuwze** [comment]
Thank you @borkdude! That is exactly what I looking for!

**Comment by candid82** [comment]
Thank you @borkdude for chiming in! Really appreciate it.
