### ISSUE TITLE
"Parse error: Unable to resolve symbol:" for property call syntax in CLJS

### ISSUE THREAD

**Issue by wasamasa** [candid82/joker#61]
Problematic code:

```clojure
(.-location js/document)
```

This throws the error in the title. Changing it to `js/document.location` silences it.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/40cf33f69f5fb32e1580a3f40dc9b589c443b029

**Comment by candid82** [comment]
Thanks for reporting btw!
