### ISSUE TITLE
Complex ns requires

### ISSUE THREAD

**Issue by OscarMarshall** [candid82/joker#65]
In order to import es6 libraries, [shadow-cljs](https://github.com/thheller/shadow-cljs) adds the require keyword `:default` (`(:require ["module-name" :default defaultExport])`). Could that be added to the linter? Functionally, joker could pretend that it means `:as` and have linting work correctly.

Also, I've noticed that `:rename` seems to not lint correctly (`(require '[clojure.repl :as r :rename {doc d}])`). It's a regular clojure thing (but doesn't seem to be documented).

**Comment by candid82** [comment]
`:default` should now work (see https://github.com/candid82/joker/commit/e20517b85a84149938d03a261d0311fb96313c1f). I'll look into `:rename` later.

**Comment by candid82** [comment]
@OscarMarshall I've looked into `:rename` and it appears to work fine. Well, my previous commit (https://github.com/candid82/joker/commit/e20517b85a84149938d03a261d0311fb96313c1f) actually broke it, but it's now fixed (https://github.com/candid82/joker/commit/b15fceb9ed4d99828d1f63bf3da5cb49d186edfa) The current released version ([v0.9.4](https://github.com/candid82/joker/releases/tag/v0.9.4)) should work fine with `:rename`. See [this test](https://github.com/candid82/joker/tree/master/tests/linter/ns-9).

Note that the example you provided is incorrect: `:rename` only makes sense in conjunction with `:refer`: `(require '[clojure.repl :as r :refer [doc] :rename {doc d}])`
