### ISSUE TITLE
deps.edn

### ISSUE THREAD

**Issue by agzam** [candid82/joker#66]
What would be the best way to ignore deps.edn? it highlights things for no reason - a bit annoying. Thanks!

**Comment by candid82** [comment]
Can you provide an example of deps.edn file that's causing false positives?

**Comment by agzam** [comment]
This is one example:

![screenshot from 2018-07-10 23-13-12](https://user-images.githubusercontent.com/1091022/42553725-d24af20e-8496-11e8-944d-fa88588795a2.png)

see the highlighted stuff?

**Comment by candid82** [comment]
OK, this is flycheck-joker issue (I am assuming you are using emacs). It lints EDN files as clojure source code. Joker knows how to lint EDN files, but flycheck-joker runs it with [wrong arguments] for EDN files. (https://github.com/candid82/flycheck-joker/blob/master/flycheck-joker.el#L51-L61). Compare:
```
lint EDN dialect
$ joker --lintedn -- < deps.edn

vs.
lint Clojure dialect (default)
$ joker --lint -- < deps.edn
```
flycheck-joker should pass `--lint` for Clojure files and `--lintedn` for EDN files, similarly to how sublime plugin [does it](https://github.com/candid82/SublimeLinter-contrib-joker/blob/master/linter.py#L23-L32)
I don't use emacs so it may take some time for me to fix it. Feel free to send a PR if you are interested in helping out ;)

**Comment by agzam** [comment]
Thanks for clarifying this. I just pushed https://github.com/candid82/flycheck-joker/pull/3

**Comment by candid82** [comment]
Thanks a lot!
