### ISSUE TITLE
destructuring namespaced keywords from macro bindings

### ISSUE THREAD

**Issue by mattly** [candid82/joker#67]
This does not yield an error:

``` clj
(rum/defc Foo < rum/static [{:keys [foo]}] [:div (str foo)])
```

Where this yields `unable to resolve symbol: foo`:

``` clj
(rum/defc Foo < rum/static [{:keys [bar/foo]}] [:div (str foo)])
```

Joker handles destructuring namespaced keywords in normal `let` bindings just fine, so this was unexpected.

**Comment by candid82** [comment]
Joker doesn't know what `rum/defc` expands to, hence the error. There is a solution though. Using the latest master, you should be able to "teach" Joker what `rum/defc` means by adding the following code to `.jokerd/linter.clj` file:

```clojure
(ns rum.core)

(defmacro defc [& params]
	(let [[name _ _ arg-vector & body] params]
   `(defn ~name ~arg-vector ~@body)))


(in-ns 'user)
```

It basically tells Joker to expand `rum.core/defc` to regular `defn` before linting.

**Comment by mattly** [comment]
Thanks!
