### ISSUE TITLE
Unable to resolve symbol thrown?

### ISSUE THREAD

**Issue by heyarne** [candid82/joker#68]
Hi!
I'm getting a linter error for the following [special from of `cljs.test/is`](https://cljs.github.io/api/cljs.test/#is):

> `(is (thrown? c body))` checks that an instance of c is thrown from
body, fails if not; then returns the thing thrown.

The linter reports `Unable to resolve symbol: thrown?`.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/2a893c11b732758fb54e246fc947d80f8cbf9237
You can also add `cljs.test/is` to `known-macros` in your `.joker` file if you don't want to wait for the next release. See https://github.com/candid82/joker#reducing-false-positives for details.
