### ISSUE TITLE
Supporting `.joker` in project root path

### ISSUE THREAD

**Issue by rmuslimov** [candid82/joker#7]
> The file is called .joker and should be in your home directory. It should contain a single map with :known-macros key

Why can't we use `.joker` in root directory of the project?
We just want to make same linter options for whole team. It would be great if along with `~/.joker`, it will look at project root directory. 
Thanks!

**Comment by candid82** [comment]
Make sense to me. Even though `:known-macros` are fully qualified symbols and (at least in theory) should be applicable to any project (so you can keep piling up new macros you come across to `~/.joker`), I can see how it would be convenient to share a joker file tailored to a specific project by committing it to source control with the project's source. I'll look into it.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/c71db44d33b2da5431156ddfc54427dfac145389

**Comment by rmuslimov** [comment]
Great, thanks!
