### ISSUE TITLE
Linter incorrectly flagging slurp with 3 arguments

### ISSUE THREAD

**Issue by morrifeldman** [candid82/joker#71]
The linter is flagging the 3 argument form of `slurp`, meaning `(slurp "a-file-name" :encoding "UTF-8")`, which is valid clojure, gives `Parse warning: Wrong number of args (3) passed to core/slurp`.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/6beb22f0efa01618717e636e7d3f8c31bd351e70
