### ISSUE TITLE
False positive on fully-qualified class names

### ISSUE THREAD

**Issue by achesnais** [candid82/joker#72]
When refering to classes in code, Joker will signal an error if you use the fully qualified classname instead of a simple class name:

```clojure
(ns test.ns
  (:import datomic.db.Db))

(defprotocol ITest
  (x [this]))

(extend-protocol ITest
  datomic.db.Db ;; <- joker says: unable to resolve symbol
  (x [this] (println "do something")))
```

In quite a few contexts it's actually nice to be able to use full class names for clarity. If would be great if Joker could recognise these as well!

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/3b42505ed25d1b15ddd3b95dcd54dd23f960e849
