### ISSUE TITLE
Add Profiling Support

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#75]
Add support (via command-line options) for the pkg/profile and runtime/pprof profilers.

**Comment by jcburley** [comment]
(Yes, I'm volunteering to do it, and am in fact going to start work on it now on my own fork, because I'm looking into how fast Joker can potentially become compared to other Lisp interpreters, except for Clojure and Lumo/ClojureScript, which it already seems to have left well behind in its dust....)

**Comment by candid82** [comment]
That'd be great! I wanted to profile joker as well but just never got to it. 
Joker is actually very slow interpreter, but its startup time is OK. I am experimenting with the ways to speed it up further by pre-parsing joker.core and standard library code, but this is still work in progress.

**Comment by jcburley** [comment]
https://github.com/jcburley/joker/commit/cae9e7d6108cbb8c44c5c61c9053f452fa0699ac is the first of several commits that are queued up for a future PR (as with all of my work today, they follow my proposed changes to clean up command-line processing -- mainly because I wanted to avoid having even more command-line options to rework in that fashion).

**Comment by jcburley** [comment]
Fixed by https://github.com/candid82/joker/pull/88.

(If there's interest, block profiling and such could be added....)
