### ISSUE TITLE
Can I import libraries from golang?

### ISSUE THREAD

**Issue by mrkaspa** [candid82/joker#8]

**Comment by candid82** [comment]
No. At the moment the only way to interact with Go is by creating bindings similarly to how it's done for standard namespaces. For example, `joker.string` is, for the most part, a proxy to Go's `strings` package. Even then, there is no way to dynamically load bindings to an arbitrary Go library at runtime.

**Comment by candid82** [comment]
@mrkaspa Closing this but let me know if you have any other questions. Better interoperability with Go is in long term plans but it's not immediately obvious to me how to implement what you are asking.

**Comment by mrkaspa** [comment]
@candid82 thank nice project!
