### ISSUE TITLE
"No reader function for tag queue" error when reading CLJS code inside .cljc file

### ISSUE THREAD

**Issue by bhb** [candid82/joker#91]
Repro:

1. Install joker 0.9.7
2. Create file `foo.cljc`

```clojure
#?(:cljs
   (let [x #queue []]
     x))

(comment "done") ;; just here to avoid EOF warning
```
3. Run `joker --lint foo.cljc`

Expected: No errors
Actual: "Read warning: No reader function for tag queue", joker exits with status 1.

Note: joker 0.9.2 did not report this error. 

Note that this error does not occur when linting a file like `foo.cljs`

```clojure
(let [x #queue []]
  x
```

**Comment by candid82** [comment]
Joker lints *.cljc files with Clojure dialect, not ClojureScript, and doesn't currently support dynamic dialect switching inside reader conditionals. You can silence that warning by adding `:known-tags [queue]` to your .joker file.

**Comment by bhb** [comment]
Ah, I see. I'll use your suggestion to add `:known-tags`. Thanks for all your work on joker, it's really useful!
