### ISSUE TITLE
Undetected unused binding in let 

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#96]
Example:

```
(let [a 10
      a 11]
  a)
```

The first a binding isn't used at all. Can joker linter detect and report this?

**Comment by candid82** [comment]
Implemented by https://github.com/candid82/joker/commit/bc7e37cb6c5df3ac1fb16df176ab1b4d8c1711b9. Note that if a binding exists just for side effects, it will need to be named `_` (underscore) for the linter to ignore it. 

This will result in a warning:

```clojure
(let [a (launch-rockets) 
      a 1] a)
```
This will not:

```clojure
(let [_ (launch-rockets) 
      _ (launch-more-rockets)
      a 1] a)
```
