### ISSUE TITLE
Unused function arguments

### ISSUE THREAD

**Issue by borkdude** [candid82/joker#97]
Example:

```
(defn foo [a b]
  a)
```
Can joker linter detect and report that argument b isn't used?

**Comment by candid82** [comment]
Implemented by https://github.com/candid82/joker/commit/960eca400c1365b2ace663948ee87e451fd44656

The warning is behind `:unused-fn-parameters` flag (defaults to false).
If parameter's name starts with `_` (underscore), the warning won't be issued. The same is now the case for unused let bindings.
Also, "fn with empty body" warning has been implemented. It is behind `:fn-with-empty-body` flag (defaults to true).
