### ISSUE TITLE
Clojure 1.10 compatibility

### ISSUE THREAD

**Issue by seancorfield** [candid82/joker#98]
The following new `clojure.core` functions have been added:
* `ex-cause`, `ex-message` (to match ClojureScript)
* `tap>`, `add-tap`, `remove-tap` -- debugging functions
* `read+string`, `PrintWriter-on` -- prepl support functions

Currently, Joker flags these as `Parse error: Unable to resolve symbol:`

**Comment by candid82** [comment]
Thanks for reporting! This has been addressed in master.

**Comment by seancorfield** [comment]
Thank you! I look forward to a new release since we're already using 1.10 Beta 4 in production!

**Comment by seancorfield** [comment]
And, by the way, can I just say that I **love** Joker as a linter! Thank you for making it!
