### ISSUE TITLE
Integer Exit Code Not Returned by joker.os/sh 

### ISSUE THREAD

**Issue by jcburley** [candid82/joker#99]
Clojure provides the actual exit code returned by the program run via:

```
user=> (require '(clojure.java [shell :as sh]))
nil
user=> (sh/sh "sh" "-c" "exit 5")
{:exit 5, :out "", :err ""}
user=> (sh/sh "sh" "-c" "exit 0")
{:exit 0, :out "", :err ""}
user=>
```

Whereas Joker returns it only embedded within an (undocumented) string:

```
user=> (require '(joker [os :as os]))
nil
user=> (os/sh "sh" "-c" "exit 5")
{:success false, :err-msg "exit status 5", :out "", :err ""}
user=>
```

While `:err-msg` is nice, it should be documented, and an `:exit` key/value should also be returned with the actual error code.

**Comment by jcburley** [comment]
FYI, I've hit a major milestone here in that, with the PR (my branch), I'm now using a Joker script on my Internet-facing server!

The script is one small piece of my arcane, but generally effective, SMTP server, including spam filtering and the like -- nothing worth publishing at this time. For now, it's invoked along with the original `bash` script from which it was converted, and the outputs compared (this is probably overkill at this point).

But it's a start, and it did require me to increase memory limits (more specifically, I had to change the the **daemontools** `softlimit` command line to use `-d` and `-s` instead of just `-m`, for which no value seemed to support Joker running -- something weird about including `-a` with `-d` and/or `-s`, which `-m` does automatically, because they worked independently).

I plan to slowly "evolve" more of my own scripts over to Joker scripts, then probably more of the main mailserver code, and at some point in there start really leveraging the power of Clojure. (Some of the conversions might well be to ClojureScript or Clojure proper; I needed Joker to handle the performance requirements for oft-invoked scripts "on the edges" of the architecture.)

Thanks again for creating Joker!

**Comment by candid82** [comment]
This is great! Glad Joker is being used for scripting, which is certainly one of the use cases I had in mind for it (although most people use it purely as Clojure linter). We use it for “Devops” scripting on our team at work. We are a Clojure centric team and being able to write scripts in (almost) Clojure is nice.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/pull/100. Thanks @jcburley!
